const std = @import("std");
const zigmodu = @import("zigmodu");
const http = zigmodu.http;
const service = @import("service.zig");
const persist = @import("persistence.zig");

/// Catalog HTTP API — ComptimeRouter (`docs/ROUTE_TABLE.md`).
/// The generic product CRUD surface (list/create/get/update/delete) is
/// generated by `zent_crud.CrudApi` in main.zig; this type only keeps the
/// bespoke endpoints (tenant bootstrap, counts, search, bulk, SSE) that
/// coexist with it under the same module_name/nest.
pub fn CatalogApi(comptime Service: type) type {
    return struct {
        const Self = @This();
        svc: *Service,

        pub const module_name = "catalog";
        pub const nest = .{};
        pub const State = Self;

        const CreateTenantQ = struct { name: []const u8, domain: []const u8 };
        const SearchProductQ = struct { tenant_id: i64, q: []const u8 };
        // bulk = 按 id upsert（id 必填：插入新行或更新既有行）。
        const BulkProduct = struct { id: i64, tenant_id: i64, name: []const u8, price_cents: i64 = 0 };

        const create_tenant_params = http.openApiParamsFromStruct(CreateTenantQ, .query);
        const search_product_params = http.openApiParamsFromStruct(SearchProductQ, .query);

        pub const routes = [_]http.RouteSpec(State){
            .{ .method = .POST, .path = "tenants", .handler = createTenant, .meta = .{ .auth = .public, .openapi_params = &create_tenant_params } },
            .{ .method = .GET, .path = "products/counts", .handler = countProducts, .meta = .{ .auth = .public } },
            .{ .method = .GET, .path = "products/search", .handler = searchProducts, .meta = .{ .auth = .public, .openapi_params = &search_product_params } },
            .{ .method = .POST, .path = "products/bulk", .handler = upsertProducts, .meta = .{ .auth = .public } },
        };

        pub const sse_routes = [_]http.SseSpec(State){
            .{ .path = "events", .handler = streamEvents, .meta = .{ .auth = .public } },
        };

        pub fn init(svc: *Service) Self {
            return .{ .svc = svc };
        }

        fn createTenant(ctx: *http.Context, self: *State) !void {
            const q = http.extractQuery(ctx, CreateTenantQ) catch |err| return http.respondErr(ctx, err);
            const id = self.svc.createTenant(q.name, q.domain) catch |err| return http.respondErr(ctx, err);
            const resp = try std.fmt.allocPrint(ctx.allocator, "{{\"id\":{d}}}", .{id});
            defer ctx.allocator.free(resp);
            try ctx.json(201, resp);
        }

        fn writeProductsJson(ctx: *http.Context, rows: []const persist.CatalogStore.ProductRow) !void {
            var buf = std.ArrayList(u8).empty;
            defer buf.deinit(ctx.allocator);
            try buf.appendSlice(ctx.allocator, "{\"products\":[");
            for (rows, 0..) |r, i| {
                if (i > 0) try buf.appendSlice(ctx.allocator, ",");
                const entry = try std.fmt.allocPrint(ctx.allocator,
                    \\{{"id":{d},"tenant_id":{d},"name":"{s}","price_cents":{d}}}
                , .{ r.id, r.tenant_id, r.name, r.price_cents });
                defer ctx.allocator.free(entry);
                try buf.appendSlice(ctx.allocator, entry);
            }
            try buf.appendSlice(ctx.allocator, "]}");
            try ctx.json(200, buf.items);
        }

        fn countProducts(ctx: *http.Context, self: *State) !void {
            const rows = self.svc.countProductsByTenant() catch |err| return http.respondErr(ctx, err);
            defer ctx.allocator.free(rows);
            var buf = std.ArrayList(u8).empty;
            defer buf.deinit(ctx.allocator);
            try buf.appendSlice(ctx.allocator, "{\"counts\":[");
            for (rows, 0..) |r, i| {
                if (i > 0) try buf.appendSlice(ctx.allocator, ",");
                const entry = try std.fmt.allocPrint(ctx.allocator, "{{\"tenant_id\":{d},\"count\":{d}}}", .{ r.tenant_id, r.count });
                defer ctx.allocator.free(entry);
                try buf.appendSlice(ctx.allocator, entry);
            }
            try buf.appendSlice(ctx.allocator, "]}");
            try ctx.json(200, buf.items);
        }

        fn searchProducts(ctx: *http.Context, self: *State) !void {
            const q = http.extractQuery(ctx, SearchProductQ) catch |err| return http.respondErr(ctx, err);
            const rows = self.svc.searchProducts(q.tenant_id, q.q) catch |err| return http.respondErr(ctx, err);
            defer self.svc.freeProducts(rows);
            try writeProductsJson(ctx, rows);
        }

        fn upsertProducts(ctx: *http.Context, self: *State) !void {
            const items = ctx.bindJson([]BulkProduct) catch return ctx.json(400, "{\"error\":\"invalid body\"}");
            var rows = std.ArrayList(persist.CatalogStore.ProductRow).empty;
            defer rows.deinit(ctx.allocator);
            for (items) |it| {
                try rows.append(ctx.allocator, .{
                    .id = it.id,
                    .tenant_id = it.tenant_id,
                    .name = it.name,
                    .price_cents = it.price_cents,
                });
            }
            self.svc.upsertProducts(rows.items) catch |err| return http.respondErr(ctx, err);
            try ctx.json(200, "{\"ok\":true}");
        }

        /// Demo SSE: one tick then done (requires live stream in production).
        fn streamEvents(ctx: *http.Context, _: *State) !void {
            var writer = try http.sse(ctx);
            try writer.sendEvent("hello", "{\"source\":\"catalog\"}");
            try writer.done();
        }
    };
}

pub const DefaultCatalogApi = CatalogApi(service.CatalogService);
