//! Auto-generated HTTP API for module: delivery
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const DeliveryApi = struct {
    service: *service.DeliveryService,

    pub fn init(service_ptr: *service.DeliveryService) DeliveryApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *DeliveryApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_deliverys", listZmoduDeliverys, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_deliverys/:id", getZmoduDelivery, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_deliverys", createZmoduDelivery, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_deliverys/:id", updateZmoduDelivery, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_deliverys/:id", deleteZmoduDelivery, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_delivery_rules", listZmoduDeliveryRules, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_delivery_rules/:id", getZmoduDeliveryRule, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_delivery_rules", createZmoduDeliveryRule, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_delivery_rules/:id", updateZmoduDeliveryRule, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_delivery_rules/:id", deleteZmoduDeliveryRule, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_delivery_settings", listZmoduDeliverySettings, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_delivery_settings/:id", getZmoduDeliverySetting, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_delivery_settings", createZmoduDeliverySetting, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_delivery_settings/:id", updateZmoduDeliverySetting, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_delivery_settings/:id", deleteZmoduDeliverySetting, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_delivery_templates", listZmoduDeliveryTemplates, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_delivery_templates/:id", getZmoduDeliveryTemplate, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_delivery_templates", createZmoduDeliveryTemplate, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_delivery_templates/:id", updateZmoduDeliveryTemplate, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_delivery_templates/:id", deleteZmoduDeliveryTemplate, @ptrCast(@alignCast(self)));
    }

    fn listZmoduDeliverys(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[delivery] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[delivery] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduDeliverys(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduDelivery(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[delivery] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[delivery] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduDelivery(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduDelivery(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduDelivery) catch {
            std.log.warn("[delivery] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduDelivery(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduDelivery(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduDelivery) catch {
            std.log.warn("[delivery] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduDelivery(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduDelivery(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[delivery] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduDelivery(id);
        try ctx.json(204, "");
    }

    fn listZmoduDeliveryRules(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[delivery] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[delivery] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduDeliveryRules(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduDeliveryRule(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[delivery] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[delivery] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduDeliveryRule(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduDeliveryRule(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduDeliveryRule) catch {
            std.log.warn("[delivery] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduDeliveryRule(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduDeliveryRule(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduDeliveryRule) catch {
            std.log.warn("[delivery] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduDeliveryRule(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduDeliveryRule(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[delivery] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduDeliveryRule(id);
        try ctx.json(204, "");
    }

    fn listZmoduDeliverySettings(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[delivery] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[delivery] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduDeliverySettings(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduDeliverySetting(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[delivery] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[delivery] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduDeliverySetting(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduDeliverySetting(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduDeliverySetting) catch {
            std.log.warn("[delivery] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduDeliverySetting(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduDeliverySetting(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduDeliverySetting) catch {
            std.log.warn("[delivery] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduDeliverySetting(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduDeliverySetting(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[delivery] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduDeliverySetting(id);
        try ctx.json(204, "");
    }

    fn listZmoduDeliveryTemplates(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[delivery] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[delivery] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduDeliveryTemplates(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduDeliveryTemplate(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[delivery] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[delivery] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduDeliveryTemplate(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduDeliveryTemplate(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduDeliveryTemplate) catch {
            std.log.warn("[delivery] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduDeliveryTemplate(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduDeliveryTemplate(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduDeliveryTemplate) catch {
            std.log.warn("[delivery] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduDeliveryTemplate(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduDeliveryTemplate(ctx: *zigmodu.http_server.Context) !void {
        const self: *DeliveryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[delivery] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduDeliveryTemplate(id);
        try ctx.json(204, "");
    }

};
