//! Auto-generated models for module: message
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduMessage = struct {
    pub const sql_table_name: []const u8 = "zmodu_message";
    message_id: i64,
    message_name: ?[]const u8,
    message_ename: ?[]const u8,
    message_to: ?i64,
    message_type: ?i64,
    remark: ?[]const u8,
    sort: ?i64,
    is_delete: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("message_id");
        try jws.write(self.message_id);
        try jws.objectField("message_name");
        if (self.message_name) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("message_ename");
        if (self.message_ename) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("message_to");
        if (self.message_to) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("message_type");
        if (self.message_type) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("remark");
        if (self.remark) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("sort");
        if (self.sort) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduMessageField = struct {
    pub const sql_table_name: []const u8 = "zmodu_message_field";
    message_field_id: i64,
    message_id: i64,
    field_name: ?[]const u8,
    field_ename: ?[]const u8,
    filed_value: ?[]const u8,
    is_var: ?i64,
    sort: ?i64,
    is_delete: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("message_field_id");
        try jws.write(self.message_field_id);
        try jws.objectField("message_id");
        try jws.write(self.message_id);
        try jws.objectField("field_name");
        if (self.field_name) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("field_ename");
        if (self.field_ename) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("filed_value");
        if (self.filed_value) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_var");
        if (self.is_var) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("sort");
        if (self.sort) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduMessageSettings = struct {
    pub const sql_table_name: []const u8 = "zmodu_message_settings";
    message_settings_id: i64,
    app_id: i64,
    message_id: i64,
    sms_status: i64,
    sms_template: ?[]const u8,
    mp_status: i64,
    mp_template: ?[]const u8,
    wx_status: i64,
    wx_template: ?[]const u8,
    mt_status: i64,
    mt_template: ?[]const u8,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("message_settings_id");
        try jws.write(self.message_settings_id);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("message_id");
        try jws.write(self.message_id);
        try jws.objectField("sms_status");
        try jws.write(self.sms_status);
        try jws.objectField("sms_template");
        if (self.sms_template) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("mp_status");
        try jws.write(self.mp_status);
        try jws.objectField("mp_template");
        if (self.mp_template) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("wx_status");
        try jws.write(self.wx_status);
        try jws.objectField("wx_template");
        if (self.wx_template) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("mt_status");
        try jws.write(self.mt_status);
        try jws.objectField("mt_template");
        if (self.mt_template) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

