const std = @import("std");
const zigmodu = @import("zigmodu");
const data = zigmodu.data;

pub fn apply(client: *data.Client) !void {
    const ddl =
        \\CREATE TABLE IF NOT EXISTS zmodu_order (
        \\  order_id INTEGER PRIMARY KEY AUTOINCREMENT,
        \\  order_no TEXT NOT NULL DEFAULT '',
        \\  total_price REAL NOT NULL DEFAULT 0,
        \\  order_price REAL NOT NULL DEFAULT 0,
        \\  coupon_id INTEGER NOT NULL DEFAULT 0,
        \\  coupon_money REAL NOT NULL DEFAULT 0,
        \\  coupon_id_sys INTEGER DEFAULT 0,
        \\  coupon_money_sys REAL DEFAULT 0,
        \\  points_money REAL NOT NULL DEFAULT 0,
        \\  points_num REAL NOT NULL DEFAULT 0,
        \\  pay_price REAL NOT NULL DEFAULT 0,
        \\  update_price REAL NOT NULL DEFAULT 0,
        \\  fullreduce_money REAL DEFAULT 0,
        \\  fullreduce_remark TEXT DEFAULT '',
        \\  product_reduce_money REAL DEFAULT 0,
        \\  buyer_remark TEXT,
        \\  pay_type INTEGER NOT NULL DEFAULT 20,
        \\  pay_source TEXT DEFAULT '',
        \\  pay_status INTEGER NOT NULL DEFAULT 10,
        \\  pay_time INTEGER NOT NULL DEFAULT 0,
        \\  pay_end_time INTEGER DEFAULT 0,
        \\  delivery_type INTEGER NOT NULL DEFAULT 10,
        \\  extract_store_id INTEGER NOT NULL DEFAULT 0,
        \\  extract_clerk_id INTEGER NOT NULL DEFAULT 0,
        \\  express_price REAL NOT NULL DEFAULT 0,
        \\  express_id INTEGER NOT NULL DEFAULT 0,
        \\  express_company TEXT NOT NULL DEFAULT '',
        \\  express_no TEXT NOT NULL DEFAULT '',
        \\  delivery_status INTEGER NOT NULL DEFAULT 10,
        \\  delivery_time INTEGER NOT NULL DEFAULT 0,
        \\  receipt_status INTEGER NOT NULL DEFAULT 10,
        \\  receipt_time INTEGER NOT NULL DEFAULT 0,
        \\  order_status INTEGER NOT NULL DEFAULT 10,
        \\  points_bonus REAL NOT NULL DEFAULT 0,
        \\  is_settled INTEGER NOT NULL DEFAULT 0,
        \\  transaction_id TEXT NOT NULL DEFAULT '',
        \\  is_comment INTEGER NOT NULL DEFAULT 0,
        \\  order_source INTEGER NOT NULL DEFAULT 10,
        \\  user_id INTEGER NOT NULL DEFAULT 0,
        \\  is_refund INTEGER DEFAULT 0,
        \\  assemble_status INTEGER DEFAULT 0,
        \\  activity_id INTEGER DEFAULT 0,
        \\  is_agent INTEGER DEFAULT 0,
        \\  shop_supplier_id INTEGER DEFAULT 0,
        \\  supplier_money REAL DEFAULT 0,
        \\  sys_money REAL DEFAULT 0,
        \\  room_id INTEGER DEFAULT 0,
        \\  cancel_remark TEXT NOT NULL DEFAULT '',
        \\  virtual_auto INTEGER NOT NULL DEFAULT 0,
        \\  virtual_content TEXT,
        \\  balance REAL NOT NULL DEFAULT 0,
        \\  online_money REAL NOT NULL DEFAULT 0,
        \\  refund_money REAL NOT NULL DEFAULT 0,
        \\  trade_no TEXT NOT NULL DEFAULT '',
        \\  wx_delivery_status INTEGER NOT NULL DEFAULT 10,
        \\  is_single INTEGER DEFAULT 0,
        \\  task_id TEXT NOT NULL DEFAULT '',
        \\  return_num TEXT NOT NULL DEFAULT '',
        \\  label TEXT NOT NULL DEFAULT '',
        \\  kd_order_num TEXT NOT NULL DEFAULT '',
        \\  is_label INTEGER NOT NULL DEFAULT 0,
        \\  label_print_type INTEGER NOT NULL DEFAULT 0,
        \\  template_id INTEGER NOT NULL DEFAULT 0,
        \\  setting_id INTEGER NOT NULL DEFAULT 0,
        \\  address_id INTEGER NOT NULL DEFAULT 0,
        \\  custom_form TEXT,
        \\  delete_time INTEGER NOT NULL DEFAULT 0,
        \\  is_delete INTEGER NOT NULL DEFAULT 0,
        \\  app_id INTEGER NOT NULL DEFAULT 0,
        \\  create_time INTEGER NOT NULL DEFAULT 0,
        \\  update_time INTEGER NOT NULL DEFAULT 0
        \\)
    ;
    _ = try client.exec(ddl, &.{});
    std.log.info("[schema] zmodu_order table ready", .{});
}
