//! Auto-generated ORM persistence for module: advance
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const AdvancePersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) AdvancePersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduAdvanceProductRepo(self: *AdvancePersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduAdvanceProduct) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduAdvanceProductSkuRepo(self: *AdvancePersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduAdvanceProductSku) {
        return .{ .orm = &self.orm };
    }

};
