//! Auto-generated service for module: advance
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=advance | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const AdvanceService = struct {
    persistence: *persistence.AdvancePersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(AdvanceEvent),

    pub fn init(persistence_ptr: *persistence.AdvancePersistence) AdvanceService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *AdvanceService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *AdvanceService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *AdvanceService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduAdvanceProducts(self: *AdvanceService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduAdvanceProduct) {
        var repo = self.persistence.zmoduAdvanceProductRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduAdvanceProduct(self: *AdvanceService, id: i64) !?model.ZmoduAdvanceProduct {
        var repo = self.persistence.zmoduAdvanceProductRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduAdvanceProduct(self: *AdvanceService, entity: model.ZmoduAdvanceProduct) !model.ZmoduAdvanceProduct {
        var repo = self.persistence.zmoduAdvanceProductRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduAdvanceProduct(self: *AdvanceService, entity: model.ZmoduAdvanceProduct) !void {
        var repo = self.persistence.zmoduAdvanceProductRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduAdvanceProduct(self: *AdvanceService, id: i64) !void {
        var repo = self.persistence.zmoduAdvanceProductRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduAdvanceProductSkus(self: *AdvanceService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduAdvanceProductSku) {
        var repo = self.persistence.zmoduAdvanceProductSkuRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduAdvanceProductSku(self: *AdvanceService, id: i64) !?model.ZmoduAdvanceProductSku {
        var repo = self.persistence.zmoduAdvanceProductSkuRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduAdvanceProductSku(self: *AdvanceService, entity: model.ZmoduAdvanceProductSku) !model.ZmoduAdvanceProductSku {
        var repo = self.persistence.zmoduAdvanceProductSkuRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduAdvanceProductSku(self: *AdvanceService, entity: model.ZmoduAdvanceProductSku) !void {
        var repo = self.persistence.zmoduAdvanceProductSkuRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduAdvanceProductSku(self: *AdvanceService, id: i64) !void {
        var repo = self.persistence.zmoduAdvanceProductSkuRepo();
        return try repo.delete(id);
    }

};
