//! Auto-generated models for module: spec
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduSpec = struct {
    pub const sql_table_name: []const u8 = "zmodu_spec";
    spec_id: i64,
    spec_name: []const u8,
    app_id: i64,
    create_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("spec_id");
        try jws.write(self.spec_id);
        try jws.objectField("spec_name");
        try jws.write(self.spec_name);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.endObject();
    }
};

pub const ZmoduSpecValue = struct {
    pub const sql_table_name: []const u8 = "zmodu_spec_value";
    spec_value_id: i64,
    spec_value: []const u8,
    spec_id: i64,
    app_id: i64,
    create_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("spec_value_id");
        try jws.write(self.spec_value_id);
        try jws.objectField("spec_value");
        try jws.write(self.spec_value);
        try jws.objectField("spec_id");
        try jws.write(self.spec_id);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.endObject();
    }
};

