//! Auto-generated HTTP API for module: lottery
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const LotteryApi = struct {
    service: *service.LotteryService,

    pub fn init(service_ptr: *service.LotteryService) LotteryApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *LotteryApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_lotterys", listZmoduLotterys, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_lotterys/:id", getZmoduLottery, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_lotterys", createZmoduLottery, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_lotterys/:id", updateZmoduLottery, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_lotterys/:id", deleteZmoduLottery, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_lottery_prizes", listZmoduLotteryPrizes, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_lottery_prizes/:id", getZmoduLotteryPrize, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_lottery_prizes", createZmoduLotteryPrize, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_lottery_prizes/:id", updateZmoduLotteryPrize, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_lottery_prizes/:id", deleteZmoduLotteryPrize, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_lottery_records", listZmoduLotteryRecords, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_lottery_records/:id", getZmoduLotteryRecord, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_lottery_records", createZmoduLotteryRecord, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_lottery_records/:id", updateZmoduLotteryRecord, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_lottery_records/:id", deleteZmoduLotteryRecord, @ptrCast(@alignCast(self)));
    }

    fn listZmoduLotterys(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[lottery] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[lottery] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduLotterys(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduLottery(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[lottery] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[lottery] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduLottery(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduLottery(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLottery) catch {
            std.log.warn("[lottery] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduLottery(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduLottery(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLottery) catch {
            std.log.warn("[lottery] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduLottery(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduLottery(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[lottery] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduLottery(id);
        try ctx.json(204, "");
    }

    fn listZmoduLotteryPrizes(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[lottery] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[lottery] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduLotteryPrizes(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduLotteryPrize(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[lottery] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[lottery] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduLotteryPrize(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduLotteryPrize(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLotteryPrize) catch {
            std.log.warn("[lottery] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduLotteryPrize(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduLotteryPrize(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLotteryPrize) catch {
            std.log.warn("[lottery] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduLotteryPrize(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduLotteryPrize(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[lottery] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduLotteryPrize(id);
        try ctx.json(204, "");
    }

    fn listZmoduLotteryRecords(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[lottery] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[lottery] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduLotteryRecords(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduLotteryRecord(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[lottery] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[lottery] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduLotteryRecord(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduLotteryRecord(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLotteryRecord) catch {
            std.log.warn("[lottery] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduLotteryRecord(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduLotteryRecord(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLotteryRecord) catch {
            std.log.warn("[lottery] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduLotteryRecord(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduLotteryRecord(ctx: *zigmodu.http_server.Context) !void {
        const self: *LotteryApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[lottery] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduLotteryRecord(id);
        try ctx.json(204, "");
    }

};
