//! Auto-generated ORM persistence for module: lottery
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const LotteryPersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) LotteryPersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduLotteryRepo(self: *LotteryPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduLottery) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduLotteryPrizeRepo(self: *LotteryPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduLotteryPrize) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduLotteryRecordRepo(self: *LotteryPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduLotteryRecord) {
        return .{ .orm = &self.orm };
    }

};
