//! Auto-generated service for module: lottery
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=lottery | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const LotteryService = struct {
    persistence: *persistence.LotteryPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(LotteryEvent),

    pub fn init(persistence_ptr: *persistence.LotteryPersistence) LotteryService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *LotteryService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *LotteryService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *LotteryService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduLotterys(self: *LotteryService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduLottery) {
        var repo = self.persistence.zmoduLotteryRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduLottery(self: *LotteryService, id: i64) !?model.ZmoduLottery {
        var repo = self.persistence.zmoduLotteryRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduLottery(self: *LotteryService, entity: model.ZmoduLottery) !model.ZmoduLottery {
        var repo = self.persistence.zmoduLotteryRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduLottery(self: *LotteryService, entity: model.ZmoduLottery) !void {
        var repo = self.persistence.zmoduLotteryRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduLottery(self: *LotteryService, id: i64) !void {
        var repo = self.persistence.zmoduLotteryRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduLotteryPrizes(self: *LotteryService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduLotteryPrize) {
        var repo = self.persistence.zmoduLotteryPrizeRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduLotteryPrize(self: *LotteryService, id: i64) !?model.ZmoduLotteryPrize {
        var repo = self.persistence.zmoduLotteryPrizeRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduLotteryPrize(self: *LotteryService, entity: model.ZmoduLotteryPrize) !model.ZmoduLotteryPrize {
        var repo = self.persistence.zmoduLotteryPrizeRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduLotteryPrize(self: *LotteryService, entity: model.ZmoduLotteryPrize) !void {
        var repo = self.persistence.zmoduLotteryPrizeRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduLotteryPrize(self: *LotteryService, id: i64) !void {
        var repo = self.persistence.zmoduLotteryPrizeRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduLotteryRecords(self: *LotteryService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduLotteryRecord) {
        var repo = self.persistence.zmoduLotteryRecordRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduLotteryRecord(self: *LotteryService, id: i64) !?model.ZmoduLotteryRecord {
        var repo = self.persistence.zmoduLotteryRecordRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduLotteryRecord(self: *LotteryService, entity: model.ZmoduLotteryRecord) !model.ZmoduLotteryRecord {
        var repo = self.persistence.zmoduLotteryRecordRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduLotteryRecord(self: *LotteryService, entity: model.ZmoduLotteryRecord) !void {
        var repo = self.persistence.zmoduLotteryRecordRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduLotteryRecord(self: *LotteryService, id: i64) !void {
        var repo = self.persistence.zmoduLotteryRecordRepo();
        return try repo.delete(id);
    }

};
