//! Auto-generated HTTP API for module: coupon
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const CouponApi = struct {
    service: *service.CouponService,

    pub fn init(service_ptr: *service.CouponService) CouponApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *CouponApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_coupons", listZmoduCoupons, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_coupons/:id", getZmoduCoupon, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_coupons", createZmoduCoupon, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_coupons/:id", updateZmoduCoupon, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_coupons/:id", deleteZmoduCoupon, @ptrCast(@alignCast(self)));
    }

    fn listZmoduCoupons(ctx: *zigmodu.http_server.Context) !void {
        const self: *CouponApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[coupon] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[coupon] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduCoupons(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduCoupon(ctx: *zigmodu.http_server.Context) !void {
        const self: *CouponApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[coupon] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[coupon] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduCoupon(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduCoupon(ctx: *zigmodu.http_server.Context) !void {
        const self: *CouponApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduCoupon) catch {
            std.log.warn("[coupon] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduCoupon(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduCoupon(ctx: *zigmodu.http_server.Context) !void {
        const self: *CouponApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduCoupon) catch {
            std.log.warn("[coupon] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduCoupon(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduCoupon(ctx: *zigmodu.http_server.Context) !void {
        const self: *CouponApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[coupon] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduCoupon(id);
        try ctx.json(204, "");
    }

};
