//! Auto-generated ORM persistence for module: coupon
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const CouponPersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) CouponPersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduCouponRepo(self: *CouponPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduCoupon) {
        return .{ .orm = &self.orm };
    }

};
