//! Auto-generated service for module: coupon
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=coupon | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const CouponService = struct {
    persistence: *persistence.CouponPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(CouponEvent),

    pub fn init(persistence_ptr: *persistence.CouponPersistence) CouponService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *CouponService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *CouponService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *CouponService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduCoupons(self: *CouponService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduCoupon) {
        var repo = self.persistence.zmoduCouponRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduCoupon(self: *CouponService, id: i64) !?model.ZmoduCoupon {
        var repo = self.persistence.zmoduCouponRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduCoupon(self: *CouponService, entity: model.ZmoduCoupon) !model.ZmoduCoupon {
        var repo = self.persistence.zmoduCouponRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduCoupon(self: *CouponService, entity: model.ZmoduCoupon) !void {
        var repo = self.persistence.zmoduCouponRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduCoupon(self: *CouponService, id: i64) !void {
        var repo = self.persistence.zmoduCouponRepo();
        return try repo.delete(id);
    }

};
