//! Auto-generated models for module: app
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduApp = struct {
    pub const sql_table_name: []const u8 = "zmodu_app";
    app_id: i64,
    app_name: ?[]const u8,
    logo: ?i64,
    passport_open: ?i64,
    passport_type: ?i64,
    is_recycle: i64,
    expire_time: ?i64,
    weixin_service: ?i64,
    pay_type: ?[]const u8,
    mchid: ?[]const u8,
    apikey: ?[]const u8,
    cert_pem: ?[]const u8,
    key_pem: ?[]const u8,
    serial_no: ?[]const u8,
    platform_pem: ?[]const u8,
    alipay_appid: ?[]const u8,
    alipay_publickey: ?[]const u8,
    alipay_privatekey: ?[]const u8,
    wx_cash_type: i64,
    alipay_cert_path: ?[]const u8,
    is_delete: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("app_name");
        if (self.app_name) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("logo");
        if (self.logo) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("passport_open");
        if (self.passport_open) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("passport_type");
        if (self.passport_type) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_recycle");
        try jws.write(self.is_recycle);
        try jws.objectField("expire_time");
        if (self.expire_time) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("weixin_service");
        if (self.weixin_service) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("pay_type");
        if (self.pay_type) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("mchid");
        if (self.mchid) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("apikey");
        if (self.apikey) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("cert_pem");
        if (self.cert_pem) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("key_pem");
        if (self.key_pem) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("serial_no");
        if (self.serial_no) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("platform_pem");
        if (self.platform_pem) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("alipay_appid");
        if (self.alipay_appid) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("alipay_publickey");
        if (self.alipay_publickey) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("alipay_privatekey");
        if (self.alipay_privatekey) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("wx_cash_type");
        try jws.write(self.wx_cash_type);
        try jws.objectField("alipay_cert_path");
        if (self.alipay_cert_path) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduAppMp = struct {
    pub const sql_table_name: []const u8 = "zmodu_app_mp";
    app_id: i64,
    mpapp_id: []const u8,
    mpapp_secret: []const u8,
    mchid: []const u8,
    apikey: []const u8,
    cert_pem: ?[]const u8,
    key_pem: ?[]const u8,
    is_recycle: i64,
    is_delete: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("mpapp_id");
        try jws.write(self.mpapp_id);
        try jws.objectField("mpapp_secret");
        try jws.write(self.mpapp_secret);
        try jws.objectField("mchid");
        try jws.write(self.mchid);
        try jws.objectField("apikey");
        try jws.write(self.apikey);
        try jws.objectField("cert_pem");
        if (self.cert_pem) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("key_pem");
        if (self.key_pem) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_recycle");
        try jws.write(self.is_recycle);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduAppOpen = struct {
    pub const sql_table_name: []const u8 = "zmodu_app_open";
    app_id: i64,
    openapp_id: []const u8,
    openapp_secret: []const u8,
    mchid: []const u8,
    apikey: []const u8,
    logo: ?[]const u8,
    cert_pem: ?[]const u8,
    key_pem: ?[]const u8,
    is_alipay: ?i64,
    alipay_appid: ?[]const u8,
    alipay_publickey: ?[]const u8,
    alipay_privatekey: ?[]const u8,
    is_recycle: i64,
    is_delete: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("openapp_id");
        try jws.write(self.openapp_id);
        try jws.objectField("openapp_secret");
        try jws.write(self.openapp_secret);
        try jws.objectField("mchid");
        try jws.write(self.mchid);
        try jws.objectField("apikey");
        try jws.write(self.apikey);
        try jws.objectField("logo");
        if (self.logo) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("cert_pem");
        if (self.cert_pem) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("key_pem");
        if (self.key_pem) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_alipay");
        if (self.is_alipay) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("alipay_appid");
        if (self.alipay_appid) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("alipay_publickey");
        if (self.alipay_publickey) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("alipay_privatekey");
        if (self.alipay_privatekey) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_recycle");
        try jws.write(self.is_recycle);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduAppUpdate = struct {
    pub const sql_table_name: []const u8 = "zmodu_app_update";
    update_id: i64,
    app_id: i64,
    version_android: []const u8,
    version_ios: ?[]const u8,
    wgt_url: ?[]const u8,
    pkg_url_android: ?[]const u8,
    pkg_url_ios: ?[]const u8,
    is_delete: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("update_id");
        try jws.write(self.update_id);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("version_android");
        try jws.write(self.version_android);
        try jws.objectField("version_ios");
        if (self.version_ios) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("wgt_url");
        if (self.wgt_url) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("pkg_url_android");
        if (self.pkg_url_android) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("pkg_url_ios");
        if (self.pkg_url_ios) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduAppWx = struct {
    pub const sql_table_name: []const u8 = "zmodu_app_wx";
    app_id: i64,
    wxapp_id: []const u8,
    wxapp_secret: []const u8,
    mchid: []const u8,
    apikey: []const u8,
    cert_pem: ?[]const u8,
    key_pem: ?[]const u8,
    is_recycle: i64,
    is_delete: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("wxapp_id");
        try jws.write(self.wxapp_id);
        try jws.objectField("wxapp_secret");
        try jws.write(self.wxapp_secret);
        try jws.objectField("mchid");
        try jws.write(self.mchid);
        try jws.objectField("apikey");
        try jws.write(self.apikey);
        try jws.objectField("cert_pem");
        if (self.cert_pem) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("key_pem");
        if (self.key_pem) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_recycle");
        try jws.write(self.is_recycle);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduAppWxLive = struct {
    pub const sql_table_name: []const u8 = "zmodu_app_wx_live";
    live_id: i64,
    name: []const u8,
    roomid: i64,
    cover_img: ?[]const u8,
    share_img: ?[]const u8,
    live_status: i64,
    anchor_name: []const u8,
    start_time: i64,
    end_time: i64,
    is_top: i64,
    is_delete: i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("live_id");
        try jws.write(self.live_id);
        try jws.objectField("name");
        try jws.write(self.name);
        try jws.objectField("roomid");
        try jws.write(self.roomid);
        try jws.objectField("cover_img");
        if (self.cover_img) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("share_img");
        if (self.share_img) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("live_status");
        try jws.write(self.live_status);
        try jws.objectField("anchor_name");
        try jws.write(self.anchor_name);
        try jws.objectField("start_time");
        try jws.write(self.start_time);
        try jws.objectField("end_time");
        try jws.write(self.end_time);
        try jws.objectField("is_top");
        try jws.write(self.is_top);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

