//! Auto-generated ORM persistence for module: plus
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const PlusPersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) PlusPersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduPlusCategoryRepo(self: *PlusPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduPlusCategory) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduPlusWxCollectionRepo(self: *PlusPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduPlusWxCollection) {
        return .{ .orm = &self.orm };
    }

};
