//! Auto-generated service for module: plus
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=plus | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const PlusService = struct {
    persistence: *persistence.PlusPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(PlusEvent),

    pub fn init(persistence_ptr: *persistence.PlusPersistence) PlusService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *PlusService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *PlusService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *PlusService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduPlusCategorys(self: *PlusService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduPlusCategory) {
        var repo = self.persistence.zmoduPlusCategoryRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduPlusCategory(self: *PlusService, id: i64) !?model.ZmoduPlusCategory {
        var repo = self.persistence.zmoduPlusCategoryRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduPlusCategory(self: *PlusService, entity: model.ZmoduPlusCategory) !model.ZmoduPlusCategory {
        var repo = self.persistence.zmoduPlusCategoryRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduPlusCategory(self: *PlusService, entity: model.ZmoduPlusCategory) !void {
        var repo = self.persistence.zmoduPlusCategoryRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduPlusCategory(self: *PlusService, id: i64) !void {
        var repo = self.persistence.zmoduPlusCategoryRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduPlusWxCollections(self: *PlusService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduPlusWxCollection) {
        var repo = self.persistence.zmoduPlusWxCollectionRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduPlusWxCollection(self: *PlusService, id: i64) !?model.ZmoduPlusWxCollection {
        var repo = self.persistence.zmoduPlusWxCollectionRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduPlusWxCollection(self: *PlusService, entity: model.ZmoduPlusWxCollection) !model.ZmoduPlusWxCollection {
        var repo = self.persistence.zmoduPlusWxCollectionRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduPlusWxCollection(self: *PlusService, entity: model.ZmoduPlusWxCollection) !void {
        var repo = self.persistence.zmoduPlusWxCollectionRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduPlusWxCollection(self: *PlusService, id: i64) !void {
        var repo = self.persistence.zmoduPlusWxCollectionRepo();
        return try repo.delete(id);
    }

};
