//! Auto-generated HTTP API for module: tag
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const TagApi = struct {
    service: *service.TagService,

    pub fn init(service_ptr: *service.TagService) TagApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *TagApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_tags", listZmoduTags, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_tags/:id", getZmoduTag, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_tags", createZmoduTag, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_tags/:id", updateZmoduTag, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_tags/:id", deleteZmoduTag, @ptrCast(@alignCast(self)));
    }

    fn listZmoduTags(ctx: *zigmodu.http_server.Context) !void {
        const self: *TagApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[tag] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[tag] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduTags(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduTag(ctx: *zigmodu.http_server.Context) !void {
        const self: *TagApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[tag] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[tag] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduTag(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduTag(ctx: *zigmodu.http_server.Context) !void {
        const self: *TagApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduTag) catch {
            std.log.warn("[tag] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduTag(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduTag(ctx: *zigmodu.http_server.Context) !void {
        const self: *TagApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduTag) catch {
            std.log.warn("[tag] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduTag(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduTag(ctx: *zigmodu.http_server.Context) !void {
        const self: *TagApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[tag] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduTag(id);
        try ctx.json(204, "");
    }

};
