//! Auto-generated models for module: tag
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduTag = struct {
    pub const sql_table_name: []const u8 = "zmodu_tag";
    tag_id: i64,
    tag_name: []const u8,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("tag_id");
        try jws.write(self.tag_id);
        try jws.objectField("tag_name");
        try jws.write(self.tag_name);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

