//! Auto-generated HTTP API for module: table
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const TableApi = struct {
    service: *service.TableService,

    pub fn init(service_ptr: *service.TableService) TableApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *TableApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_tables", listZmoduTables, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_tables/:id", getZmoduTable, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_tables", createZmoduTable, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_tables/:id", updateZmoduTable, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_tables/:id", deleteZmoduTable, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_table_records", listZmoduTableRecords, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_table_records/:id", getZmoduTableRecord, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_table_records", createZmoduTableRecord, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_table_records/:id", updateZmoduTableRecord, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_table_records/:id", deleteZmoduTableRecord, @ptrCast(@alignCast(self)));
    }

    fn listZmoduTables(ctx: *zigmodu.http_server.Context) !void {
        const self: *TableApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[table] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[table] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduTables(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduTable(ctx: *zigmodu.http_server.Context) !void {
        const self: *TableApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[table] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[table] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduTable(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduTable(ctx: *zigmodu.http_server.Context) !void {
        const self: *TableApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduTable) catch {
            std.log.warn("[table] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduTable(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduTable(ctx: *zigmodu.http_server.Context) !void {
        const self: *TableApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduTable) catch {
            std.log.warn("[table] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduTable(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduTable(ctx: *zigmodu.http_server.Context) !void {
        const self: *TableApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[table] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduTable(id);
        try ctx.json(204, "");
    }

    fn listZmoduTableRecords(ctx: *zigmodu.http_server.Context) !void {
        const self: *TableApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[table] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[table] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduTableRecords(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduTableRecord(ctx: *zigmodu.http_server.Context) !void {
        const self: *TableApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[table] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[table] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduTableRecord(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduTableRecord(ctx: *zigmodu.http_server.Context) !void {
        const self: *TableApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduTableRecord) catch {
            std.log.warn("[table] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduTableRecord(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduTableRecord(ctx: *zigmodu.http_server.Context) !void {
        const self: *TableApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduTableRecord) catch {
            std.log.warn("[table] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduTableRecord(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduTableRecord(ctx: *zigmodu.http_server.Context) !void {
        const self: *TableApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[table] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduTableRecord(id);
        try ctx.json(204, "");
    }

};
