//! Auto-generated models for module: table
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduTable = struct {
    pub const sql_table_name: []const u8 = "zmodu_table";
    table_id: i64,
    name: []const u8,
    content: []const u8,
    sort: ?i64,
    total_count: ?i64,
    is_delete: ?i64,
    app_id: i64,
    create_time: i64,
    update_time: ?i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("table_id");
        try jws.write(self.table_id);
        try jws.objectField("name");
        try jws.write(self.name);
        try jws.objectField("content");
        try jws.write(self.content);
        try jws.objectField("sort");
        if (self.sort) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("total_count");
        if (self.total_count) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_delete");
        if (self.is_delete) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        if (self.update_time) |v| try jws.write(v) else try jws.write(null);
        try jws.endObject();
    }
};

pub const ZmoduTableRecord = struct {
    pub const sql_table_name: []const u8 = "zmodu_table_record";
    table_record_id: i64,
    table_id: i64,
    content: []const u8,
    user_id: ?i64,
    is_delete: ?i64,
    app_id: i64,
    create_time: i64,
    update_time: ?i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("table_record_id");
        try jws.write(self.table_record_id);
        try jws.objectField("table_id");
        try jws.write(self.table_id);
        try jws.objectField("content");
        try jws.write(self.content);
        try jws.objectField("user_id");
        if (self.user_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_delete");
        if (self.is_delete) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        if (self.update_time) |v| try jws.write(v) else try jws.write(null);
        try jws.endObject();
    }
};

