//! Auto-generated ORM persistence for module: product
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const ProductPersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) ProductPersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduProductRepo(self: *ProductPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduProduct) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduProductImageRepo(self: *ProductPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduProductImage) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduProductReduceRepo(self: *ProductPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduProductReduce) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduProductSkuRepo(self: *ProductPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduProductSku) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduProductSpecRelRepo(self: *ProductPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduProductSpecRel) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduProductVirtualRepo(self: *ProductPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduProductVirtual) {
        return .{ .orm = &self.orm };
    }

};
