//! Auto-generated ORM persistence for module: supplier
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const SupplierPersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) SupplierPersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduSupplierRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplier) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierAccessRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierAccess) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierAccountRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierAccount) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierApplyRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierApply) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierCapitalRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierCapital) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierCashRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierCash) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierCategoryRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierCategory) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierDepositOrderRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierDepositOrder) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierDepositRefundRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierDepositRefund) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierLoginLogRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierLoginLog) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierOptLogRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierOptLog) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierRoleRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierRole) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierRoleAccessRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierRoleAccess) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierServiceRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierService) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierServiceApplyRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierServiceApply) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierServiceSecurityRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierServiceSecurity) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierUserRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierUser) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduSupplierUserRoleRepo(self: *SupplierPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSupplierUserRole) {
        return .{ .orm = &self.orm };
    }

};
