//! Auto-generated service for module: supplier
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=supplier | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const SupplierService = struct {
    persistence: *persistence.SupplierPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(SupplierEvent),

    pub fn init(persistence_ptr: *persistence.SupplierPersistence) SupplierService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *SupplierService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *SupplierService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *SupplierService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduSuppliers(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplier) {
        var repo = self.persistence.zmoduSupplierRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplier(self: *SupplierService, id: i64) !?model.ZmoduSupplier {
        var repo = self.persistence.zmoduSupplierRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplier(self: *SupplierService, entity: model.ZmoduSupplier) !model.ZmoduSupplier {
        var repo = self.persistence.zmoduSupplierRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplier(self: *SupplierService, entity: model.ZmoduSupplier) !void {
        var repo = self.persistence.zmoduSupplierRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplier(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierAccesss(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierAccess) {
        var repo = self.persistence.zmoduSupplierAccessRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierAccess(self: *SupplierService, id: i64) !?model.ZmoduSupplierAccess {
        var repo = self.persistence.zmoduSupplierAccessRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierAccess(self: *SupplierService, entity: model.ZmoduSupplierAccess) !model.ZmoduSupplierAccess {
        var repo = self.persistence.zmoduSupplierAccessRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierAccess(self: *SupplierService, entity: model.ZmoduSupplierAccess) !void {
        var repo = self.persistence.zmoduSupplierAccessRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierAccess(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierAccessRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierAccounts(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierAccount) {
        var repo = self.persistence.zmoduSupplierAccountRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierAccount(self: *SupplierService, id: i64) !?model.ZmoduSupplierAccount {
        var repo = self.persistence.zmoduSupplierAccountRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierAccount(self: *SupplierService, entity: model.ZmoduSupplierAccount) !model.ZmoduSupplierAccount {
        var repo = self.persistence.zmoduSupplierAccountRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierAccount(self: *SupplierService, entity: model.ZmoduSupplierAccount) !void {
        var repo = self.persistence.zmoduSupplierAccountRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierAccount(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierAccountRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierApplys(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierApply) {
        var repo = self.persistence.zmoduSupplierApplyRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierApply(self: *SupplierService, id: i64) !?model.ZmoduSupplierApply {
        var repo = self.persistence.zmoduSupplierApplyRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierApply(self: *SupplierService, entity: model.ZmoduSupplierApply) !model.ZmoduSupplierApply {
        var repo = self.persistence.zmoduSupplierApplyRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierApply(self: *SupplierService, entity: model.ZmoduSupplierApply) !void {
        var repo = self.persistence.zmoduSupplierApplyRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierApply(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierApplyRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierCapitals(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierCapital) {
        var repo = self.persistence.zmoduSupplierCapitalRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierCapital(self: *SupplierService, id: i64) !?model.ZmoduSupplierCapital {
        var repo = self.persistence.zmoduSupplierCapitalRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierCapital(self: *SupplierService, entity: model.ZmoduSupplierCapital) !model.ZmoduSupplierCapital {
        var repo = self.persistence.zmoduSupplierCapitalRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierCapital(self: *SupplierService, entity: model.ZmoduSupplierCapital) !void {
        var repo = self.persistence.zmoduSupplierCapitalRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierCapital(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierCapitalRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierCashs(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierCash) {
        var repo = self.persistence.zmoduSupplierCashRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierCash(self: *SupplierService, id: i64) !?model.ZmoduSupplierCash {
        var repo = self.persistence.zmoduSupplierCashRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierCash(self: *SupplierService, entity: model.ZmoduSupplierCash) !model.ZmoduSupplierCash {
        var repo = self.persistence.zmoduSupplierCashRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierCash(self: *SupplierService, entity: model.ZmoduSupplierCash) !void {
        var repo = self.persistence.zmoduSupplierCashRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierCash(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierCashRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierCategorys(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierCategory) {
        var repo = self.persistence.zmoduSupplierCategoryRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierCategory(self: *SupplierService, id: i64) !?model.ZmoduSupplierCategory {
        var repo = self.persistence.zmoduSupplierCategoryRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierCategory(self: *SupplierService, entity: model.ZmoduSupplierCategory) !model.ZmoduSupplierCategory {
        var repo = self.persistence.zmoduSupplierCategoryRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierCategory(self: *SupplierService, entity: model.ZmoduSupplierCategory) !void {
        var repo = self.persistence.zmoduSupplierCategoryRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierCategory(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierCategoryRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierDepositOrders(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierDepositOrder) {
        var repo = self.persistence.zmoduSupplierDepositOrderRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierDepositOrder(self: *SupplierService, id: i64) !?model.ZmoduSupplierDepositOrder {
        var repo = self.persistence.zmoduSupplierDepositOrderRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierDepositOrder(self: *SupplierService, entity: model.ZmoduSupplierDepositOrder) !model.ZmoduSupplierDepositOrder {
        var repo = self.persistence.zmoduSupplierDepositOrderRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierDepositOrder(self: *SupplierService, entity: model.ZmoduSupplierDepositOrder) !void {
        var repo = self.persistence.zmoduSupplierDepositOrderRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierDepositOrder(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierDepositOrderRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierDepositRefunds(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierDepositRefund) {
        var repo = self.persistence.zmoduSupplierDepositRefundRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierDepositRefund(self: *SupplierService, id: i64) !?model.ZmoduSupplierDepositRefund {
        var repo = self.persistence.zmoduSupplierDepositRefundRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierDepositRefund(self: *SupplierService, entity: model.ZmoduSupplierDepositRefund) !model.ZmoduSupplierDepositRefund {
        var repo = self.persistence.zmoduSupplierDepositRefundRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierDepositRefund(self: *SupplierService, entity: model.ZmoduSupplierDepositRefund) !void {
        var repo = self.persistence.zmoduSupplierDepositRefundRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierDepositRefund(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierDepositRefundRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierLoginLogs(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierLoginLog) {
        var repo = self.persistence.zmoduSupplierLoginLogRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierLoginLog(self: *SupplierService, id: i64) !?model.ZmoduSupplierLoginLog {
        var repo = self.persistence.zmoduSupplierLoginLogRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierLoginLog(self: *SupplierService, entity: model.ZmoduSupplierLoginLog) !model.ZmoduSupplierLoginLog {
        var repo = self.persistence.zmoduSupplierLoginLogRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierLoginLog(self: *SupplierService, entity: model.ZmoduSupplierLoginLog) !void {
        var repo = self.persistence.zmoduSupplierLoginLogRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierLoginLog(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierLoginLogRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierOptLogs(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierOptLog) {
        var repo = self.persistence.zmoduSupplierOptLogRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierOptLog(self: *SupplierService, id: i64) !?model.ZmoduSupplierOptLog {
        var repo = self.persistence.zmoduSupplierOptLogRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierOptLog(self: *SupplierService, entity: model.ZmoduSupplierOptLog) !model.ZmoduSupplierOptLog {
        var repo = self.persistence.zmoduSupplierOptLogRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierOptLog(self: *SupplierService, entity: model.ZmoduSupplierOptLog) !void {
        var repo = self.persistence.zmoduSupplierOptLogRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierOptLog(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierOptLogRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierRoles(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierRole) {
        var repo = self.persistence.zmoduSupplierRoleRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierRole(self: *SupplierService, id: i64) !?model.ZmoduSupplierRole {
        var repo = self.persistence.zmoduSupplierRoleRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierRole(self: *SupplierService, entity: model.ZmoduSupplierRole) !model.ZmoduSupplierRole {
        var repo = self.persistence.zmoduSupplierRoleRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierRole(self: *SupplierService, entity: model.ZmoduSupplierRole) !void {
        var repo = self.persistence.zmoduSupplierRoleRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierRole(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierRoleRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierRoleAccesss(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierRoleAccess) {
        var repo = self.persistence.zmoduSupplierRoleAccessRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierRoleAccess(self: *SupplierService, id: i64) !?model.ZmoduSupplierRoleAccess {
        var repo = self.persistence.zmoduSupplierRoleAccessRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierRoleAccess(self: *SupplierService, entity: model.ZmoduSupplierRoleAccess) !model.ZmoduSupplierRoleAccess {
        var repo = self.persistence.zmoduSupplierRoleAccessRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierRoleAccess(self: *SupplierService, entity: model.ZmoduSupplierRoleAccess) !void {
        var repo = self.persistence.zmoduSupplierRoleAccessRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierRoleAccess(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierRoleAccessRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierServices(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierService) {
        var repo = self.persistence.zmoduSupplierServiceRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierService(self: *SupplierService, id: i64) !?model.ZmoduSupplierService {
        var repo = self.persistence.zmoduSupplierServiceRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierService(self: *SupplierService, entity: model.ZmoduSupplierService) !model.ZmoduSupplierService {
        var repo = self.persistence.zmoduSupplierServiceRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierService(self: *SupplierService, entity: model.ZmoduSupplierService) !void {
        var repo = self.persistence.zmoduSupplierServiceRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierService(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierServiceRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierServiceApplys(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierServiceApply) {
        var repo = self.persistence.zmoduSupplierServiceApplyRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierServiceApply(self: *SupplierService, id: i64) !?model.ZmoduSupplierServiceApply {
        var repo = self.persistence.zmoduSupplierServiceApplyRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierServiceApply(self: *SupplierService, entity: model.ZmoduSupplierServiceApply) !model.ZmoduSupplierServiceApply {
        var repo = self.persistence.zmoduSupplierServiceApplyRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierServiceApply(self: *SupplierService, entity: model.ZmoduSupplierServiceApply) !void {
        var repo = self.persistence.zmoduSupplierServiceApplyRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierServiceApply(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierServiceApplyRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierServiceSecuritys(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierServiceSecurity) {
        var repo = self.persistence.zmoduSupplierServiceSecurityRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierServiceSecurity(self: *SupplierService, id: i64) !?model.ZmoduSupplierServiceSecurity {
        var repo = self.persistence.zmoduSupplierServiceSecurityRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierServiceSecurity(self: *SupplierService, entity: model.ZmoduSupplierServiceSecurity) !model.ZmoduSupplierServiceSecurity {
        var repo = self.persistence.zmoduSupplierServiceSecurityRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierServiceSecurity(self: *SupplierService, entity: model.ZmoduSupplierServiceSecurity) !void {
        var repo = self.persistence.zmoduSupplierServiceSecurityRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierServiceSecurity(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierServiceSecurityRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierUsers(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierUser) {
        var repo = self.persistence.zmoduSupplierUserRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierUser(self: *SupplierService, id: i64) !?model.ZmoduSupplierUser {
        var repo = self.persistence.zmoduSupplierUserRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierUser(self: *SupplierService, entity: model.ZmoduSupplierUser) !model.ZmoduSupplierUser {
        var repo = self.persistence.zmoduSupplierUserRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierUser(self: *SupplierService, entity: model.ZmoduSupplierUser) !void {
        var repo = self.persistence.zmoduSupplierUserRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierUser(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierUserRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSupplierUserRoles(self: *SupplierService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSupplierUserRole) {
        var repo = self.persistence.zmoduSupplierUserRoleRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSupplierUserRole(self: *SupplierService, id: i64) !?model.ZmoduSupplierUserRole {
        var repo = self.persistence.zmoduSupplierUserRoleRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSupplierUserRole(self: *SupplierService, entity: model.ZmoduSupplierUserRole) !model.ZmoduSupplierUserRole {
        var repo = self.persistence.zmoduSupplierUserRoleRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSupplierUserRole(self: *SupplierService, entity: model.ZmoduSupplierUserRole) !void {
        var repo = self.persistence.zmoduSupplierUserRoleRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSupplierUserRole(self: *SupplierService, id: i64) !void {
        var repo = self.persistence.zmoduSupplierUserRoleRepo();
        return try repo.delete(id);
    }

};
