//! Auto-generated models for module: printer
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduPrinter = struct {
    pub const sql_table_name: []const u8 = "zmodu_printer";
    printer_id: i64,
    printer_name: []const u8,
    printer_type: []const u8,
    printer_config: []const u8,
    print_times: i64,
    sort: i64,
    is_delete: i64,
    shop_supplier_id: i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("printer_id");
        try jws.write(self.printer_id);
        try jws.objectField("printer_name");
        try jws.write(self.printer_name);
        try jws.objectField("printer_type");
        try jws.write(self.printer_type);
        try jws.objectField("printer_config");
        try jws.write(self.printer_config);
        try jws.objectField("print_times");
        try jws.write(self.print_times);
        try jws.objectField("sort");
        try jws.write(self.sort);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("shop_supplier_id");
        try jws.write(self.shop_supplier_id);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

