//! Auto-generated service for module: printer
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=printer | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const PrinterService = struct {
    persistence: *persistence.PrinterPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(PrinterEvent),

    pub fn init(persistence_ptr: *persistence.PrinterPersistence) PrinterService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *PrinterService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *PrinterService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *PrinterService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduPrinters(self: *PrinterService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduPrinter) {
        var repo = self.persistence.zmoduPrinterRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduPrinter(self: *PrinterService, id: i64) !?model.ZmoduPrinter {
        var repo = self.persistence.zmoduPrinterRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduPrinter(self: *PrinterService, entity: model.ZmoduPrinter) !model.ZmoduPrinter {
        var repo = self.persistence.zmoduPrinterRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduPrinter(self: *PrinterService, entity: model.ZmoduPrinter) !void {
        var repo = self.persistence.zmoduPrinterRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduPrinter(self: *PrinterService, id: i64) !void {
        var repo = self.persistence.zmoduPrinterRepo();
        return try repo.delete(id);
    }

};
