//! Auto-generated ORM persistence for module: region
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const RegionPersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) RegionPersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduRegionRepo(self: *RegionPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduRegion) {
        return .{ .orm = &self.orm };
    }

};
