//! Auto-generated models for module: ad
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduAd = struct {
    pub const sql_table_name: []const u8 = "zmodu_ad";
    ad_id: i64,
    title: []const u8,
    image_id: i64,
    sort: i64,
    link_url: []const u8,
    name: []const u8,
    category_id: i64,
    app_id: i64,
    shop_supplier_id: i64,
    status: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("ad_id");
        try jws.write(self.ad_id);
        try jws.objectField("title");
        try jws.write(self.title);
        try jws.objectField("image_id");
        try jws.write(self.image_id);
        try jws.objectField("sort");
        try jws.write(self.sort);
        try jws.objectField("link_url");
        try jws.write(self.link_url);
        try jws.objectField("name");
        try jws.write(self.name);
        try jws.objectField("category_id");
        try jws.write(self.category_id);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("shop_supplier_id");
        try jws.write(self.shop_supplier_id);
        try jws.objectField("status");
        try jws.write(self.status);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduAdCategory = struct {
    pub const sql_table_name: []const u8 = "zmodu_ad_category";
    category_id: i64,
    name: []const u8,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("category_id");
        try jws.write(self.category_id);
        try jws.objectField("name");
        try jws.write(self.name);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

