//! Auto-generated service for module: ad
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=ad | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const AdService = struct {
    persistence: *persistence.AdPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(AdEvent),

    pub fn init(persistence_ptr: *persistence.AdPersistence) AdService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *AdService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *AdService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *AdService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduAds(self: *AdService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduAd) {
        var repo = self.persistence.zmoduAdRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduAd(self: *AdService, id: i64) !?model.ZmoduAd {
        var repo = self.persistence.zmoduAdRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduAd(self: *AdService, entity: model.ZmoduAd) !model.ZmoduAd {
        var repo = self.persistence.zmoduAdRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduAd(self: *AdService, entity: model.ZmoduAd) !void {
        var repo = self.persistence.zmoduAdRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduAd(self: *AdService, id: i64) !void {
        var repo = self.persistence.zmoduAdRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduAdCategorys(self: *AdService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduAdCategory) {
        var repo = self.persistence.zmoduAdCategoryRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduAdCategory(self: *AdService, id: i64) !?model.ZmoduAdCategory {
        var repo = self.persistence.zmoduAdCategoryRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduAdCategory(self: *AdService, entity: model.ZmoduAdCategory) !model.ZmoduAdCategory {
        var repo = self.persistence.zmoduAdCategoryRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduAdCategory(self: *AdService, entity: model.ZmoduAdCategory) !void {
        var repo = self.persistence.zmoduAdCategoryRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduAdCategory(self: *AdService, id: i64) !void {
        var repo = self.persistence.zmoduAdCategoryRepo();
        return try repo.delete(id);
    }

};
