//! Auto-generated models for module: chat
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduChat = struct {
    pub const sql_table_name: []const u8 = "zmodu_chat";
    chat_id: i64,
    status: i64,
    user_id: i64,
    app_id: i64,
    content: []const u8,
    type: i64,
    msg_type: ?i64,
    shop_supplier_id: i64,
    chat_user_id: ?i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("chat_id");
        try jws.write(self.chat_id);
        try jws.objectField("status");
        try jws.write(self.status);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("content");
        try jws.write(self.content);
        try jws.objectField("type");
        try jws.write(self.type);
        try jws.objectField("msg_type");
        if (self.msg_type) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("shop_supplier_id");
        try jws.write(self.shop_supplier_id);
        try jws.objectField("chat_user_id");
        if (self.chat_user_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduChatRelation = struct {
    pub const sql_table_name: []const u8 = "zmodu_chat_relation";
    relation_id: i64,
    user_id: i64,
    shop_supplier_id: i64,
    chat_user_id: ?i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("relation_id");
        try jws.write(self.relation_id);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("shop_supplier_id");
        try jws.write(self.shop_supplier_id);
        try jws.objectField("chat_user_id");
        if (self.chat_user_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduChatUser = struct {
    pub const sql_table_name: []const u8 = "zmodu_chat_user";
    chat_user_id: i64,
    user_id: i64,
    user_name: []const u8,
    password: []const u8,
    nick_name: []const u8,
    avatarUrl: []const u8,
    shop_supplier_id: i64,
    type: i64,
    sort: i64,
    status: i64,
    is_delete: i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("chat_user_id");
        try jws.write(self.chat_user_id);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("user_name");
        try jws.write(self.user_name);
        try jws.objectField("password");
        try jws.write(self.password);
        try jws.objectField("nick_name");
        try jws.write(self.nick_name);
        try jws.objectField("avatarUrl");
        try jws.write(self.avatarUrl);
        try jws.objectField("shop_supplier_id");
        try jws.write(self.shop_supplier_id);
        try jws.objectField("type");
        try jws.write(self.type);
        try jws.objectField("sort");
        try jws.write(self.sort);
        try jws.objectField("status");
        try jws.write(self.status);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

