//! Auto-generated ORM persistence for module: chat
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const ChatPersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) ChatPersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduChatRepo(self: *ChatPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduChat) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduChatRelationRepo(self: *ChatPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduChatRelation) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduChatUserRepo(self: *ChatPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduChatUser) {
        return .{ .orm = &self.orm };
    }

};
