//! Auto-generated service for module: chat
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=chat | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const ChatService = struct {
    persistence: *persistence.ChatPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(ChatEvent),

    pub fn init(persistence_ptr: *persistence.ChatPersistence) ChatService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *ChatService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *ChatService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *ChatService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduChats(self: *ChatService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduChat) {
        var repo = self.persistence.zmoduChatRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduChat(self: *ChatService, id: i64) !?model.ZmoduChat {
        var repo = self.persistence.zmoduChatRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduChat(self: *ChatService, entity: model.ZmoduChat) !model.ZmoduChat {
        var repo = self.persistence.zmoduChatRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduChat(self: *ChatService, entity: model.ZmoduChat) !void {
        var repo = self.persistence.zmoduChatRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduChat(self: *ChatService, id: i64) !void {
        var repo = self.persistence.zmoduChatRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduChatRelations(self: *ChatService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduChatRelation) {
        var repo = self.persistence.zmoduChatRelationRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduChatRelation(self: *ChatService, id: i64) !?model.ZmoduChatRelation {
        var repo = self.persistence.zmoduChatRelationRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduChatRelation(self: *ChatService, entity: model.ZmoduChatRelation) !model.ZmoduChatRelation {
        var repo = self.persistence.zmoduChatRelationRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduChatRelation(self: *ChatService, entity: model.ZmoduChatRelation) !void {
        var repo = self.persistence.zmoduChatRelationRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduChatRelation(self: *ChatService, id: i64) !void {
        var repo = self.persistence.zmoduChatRelationRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduChatUsers(self: *ChatService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduChatUser) {
        var repo = self.persistence.zmoduChatUserRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduChatUser(self: *ChatService, id: i64) !?model.ZmoduChatUser {
        var repo = self.persistence.zmoduChatUserRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduChatUser(self: *ChatService, entity: model.ZmoduChatUser) !model.ZmoduChatUser {
        var repo = self.persistence.zmoduChatUserRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduChatUser(self: *ChatService, entity: model.ZmoduChatUser) !void {
        var repo = self.persistence.zmoduChatUserRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduChatUser(self: *ChatService, id: i64) !void {
        var repo = self.persistence.zmoduChatUserRepo();
        return try repo.delete(id);
    }

};
