//! Auto-generated HTTP API for module: assemble
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const AssembleApi = struct {
    service: *service.AssembleService,

    pub fn init(service_ptr: *service.AssembleService) AssembleApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *AssembleApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_assemble_bills", listZmoduAssembleBills, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_assemble_bills/:id", getZmoduAssembleBill, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_assemble_bills", createZmoduAssembleBill, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_assemble_bills/:id", updateZmoduAssembleBill, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_assemble_bills/:id", deleteZmoduAssembleBill, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_assemble_bill_users", listZmoduAssembleBillUsers, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_assemble_bill_users/:id", getZmoduAssembleBillUser, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_assemble_bill_users", createZmoduAssembleBillUser, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_assemble_bill_users/:id", updateZmoduAssembleBillUser, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_assemble_bill_users/:id", deleteZmoduAssembleBillUser, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_assemble_products", listZmoduAssembleProducts, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_assemble_products/:id", getZmoduAssembleProduct, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_assemble_products", createZmoduAssembleProduct, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_assemble_products/:id", updateZmoduAssembleProduct, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_assemble_products/:id", deleteZmoduAssembleProduct, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_assemble_product_skus", listZmoduAssembleProductSkus, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_assemble_product_skus/:id", getZmoduAssembleProductSku, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_assemble_product_skus", createZmoduAssembleProductSku, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_assemble_product_skus/:id", updateZmoduAssembleProductSku, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_assemble_product_skus/:id", deleteZmoduAssembleProductSku, @ptrCast(@alignCast(self)));
    }

    fn listZmoduAssembleBills(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[assemble] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[assemble] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduAssembleBills(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduAssembleBill(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[assemble] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[assemble] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduAssembleBill(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduAssembleBill(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduAssembleBill) catch {
            std.log.warn("[assemble] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduAssembleBill(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduAssembleBill(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduAssembleBill) catch {
            std.log.warn("[assemble] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduAssembleBill(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduAssembleBill(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[assemble] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduAssembleBill(id);
        try ctx.json(204, "");
    }

    fn listZmoduAssembleBillUsers(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[assemble] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[assemble] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduAssembleBillUsers(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduAssembleBillUser(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[assemble] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[assemble] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduAssembleBillUser(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduAssembleBillUser(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduAssembleBillUser) catch {
            std.log.warn("[assemble] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduAssembleBillUser(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduAssembleBillUser(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduAssembleBillUser) catch {
            std.log.warn("[assemble] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduAssembleBillUser(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduAssembleBillUser(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[assemble] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduAssembleBillUser(id);
        try ctx.json(204, "");
    }

    fn listZmoduAssembleProducts(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[assemble] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[assemble] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduAssembleProducts(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduAssembleProduct(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[assemble] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[assemble] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduAssembleProduct(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduAssembleProduct(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduAssembleProduct) catch {
            std.log.warn("[assemble] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduAssembleProduct(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduAssembleProduct(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduAssembleProduct) catch {
            std.log.warn("[assemble] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduAssembleProduct(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduAssembleProduct(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[assemble] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduAssembleProduct(id);
        try ctx.json(204, "");
    }

    fn listZmoduAssembleProductSkus(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[assemble] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[assemble] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduAssembleProductSkus(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduAssembleProductSku(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[assemble] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[assemble] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduAssembleProductSku(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduAssembleProductSku(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduAssembleProductSku) catch {
            std.log.warn("[assemble] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduAssembleProductSku(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduAssembleProductSku(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduAssembleProductSku) catch {
            std.log.warn("[assemble] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduAssembleProductSku(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduAssembleProductSku(ctx: *zigmodu.http_server.Context) !void {
        const self: *AssembleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[assemble] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduAssembleProductSku(id);
        try ctx.json(204, "");
    }

};
