//! Auto-generated service for module: assemble
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=assemble | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const AssembleService = struct {
    persistence: *persistence.AssemblePersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(AssembleEvent),

    pub fn init(persistence_ptr: *persistence.AssemblePersistence) AssembleService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *AssembleService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *AssembleService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *AssembleService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduAssembleBills(self: *AssembleService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduAssembleBill) {
        var repo = self.persistence.zmoduAssembleBillRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduAssembleBill(self: *AssembleService, id: i64) !?model.ZmoduAssembleBill {
        var repo = self.persistence.zmoduAssembleBillRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduAssembleBill(self: *AssembleService, entity: model.ZmoduAssembleBill) !model.ZmoduAssembleBill {
        var repo = self.persistence.zmoduAssembleBillRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduAssembleBill(self: *AssembleService, entity: model.ZmoduAssembleBill) !void {
        var repo = self.persistence.zmoduAssembleBillRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduAssembleBill(self: *AssembleService, id: i64) !void {
        var repo = self.persistence.zmoduAssembleBillRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduAssembleBillUsers(self: *AssembleService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduAssembleBillUser) {
        var repo = self.persistence.zmoduAssembleBillUserRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduAssembleBillUser(self: *AssembleService, id: i64) !?model.ZmoduAssembleBillUser {
        var repo = self.persistence.zmoduAssembleBillUserRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduAssembleBillUser(self: *AssembleService, entity: model.ZmoduAssembleBillUser) !model.ZmoduAssembleBillUser {
        var repo = self.persistence.zmoduAssembleBillUserRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduAssembleBillUser(self: *AssembleService, entity: model.ZmoduAssembleBillUser) !void {
        var repo = self.persistence.zmoduAssembleBillUserRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduAssembleBillUser(self: *AssembleService, id: i64) !void {
        var repo = self.persistence.zmoduAssembleBillUserRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduAssembleProducts(self: *AssembleService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduAssembleProduct) {
        var repo = self.persistence.zmoduAssembleProductRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduAssembleProduct(self: *AssembleService, id: i64) !?model.ZmoduAssembleProduct {
        var repo = self.persistence.zmoduAssembleProductRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduAssembleProduct(self: *AssembleService, entity: model.ZmoduAssembleProduct) !model.ZmoduAssembleProduct {
        var repo = self.persistence.zmoduAssembleProductRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduAssembleProduct(self: *AssembleService, entity: model.ZmoduAssembleProduct) !void {
        var repo = self.persistence.zmoduAssembleProductRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduAssembleProduct(self: *AssembleService, id: i64) !void {
        var repo = self.persistence.zmoduAssembleProductRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduAssembleProductSkus(self: *AssembleService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduAssembleProductSku) {
        var repo = self.persistence.zmoduAssembleProductSkuRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduAssembleProductSku(self: *AssembleService, id: i64) !?model.ZmoduAssembleProductSku {
        var repo = self.persistence.zmoduAssembleProductSkuRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduAssembleProductSku(self: *AssembleService, entity: model.ZmoduAssembleProductSku) !model.ZmoduAssembleProductSku {
        var repo = self.persistence.zmoduAssembleProductSkuRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduAssembleProductSku(self: *AssembleService, entity: model.ZmoduAssembleProductSku) !void {
        var repo = self.persistence.zmoduAssembleProductSkuRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduAssembleProductSku(self: *AssembleService, id: i64) !void {
        var repo = self.persistence.zmoduAssembleProductSkuRepo();
        return try repo.delete(id);
    }

};
