//! Auto-generated models for module: sms
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduSms = struct {
    pub const sql_table_name: []const u8 = "zmodu_sms";
    sms_id: i64,
    mobile: []const u8,
    code: []const u8,
    sence: ?[]const u8,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("sms_id");
        try jws.write(self.sms_id);
        try jws.objectField("mobile");
        try jws.write(self.mobile);
        try jws.objectField("code");
        try jws.write(self.code);
        try jws.objectField("sence");
        if (self.sence) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

