//! Auto-generated ORM persistence for module: sms
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const SmsPersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) SmsPersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduSmsRepo(self: *SmsPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSms) {
        return .{ .orm = &self.orm };
    }

};
