//! Auto-generated service for module: sms
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=sms | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const SmsService = struct {
    persistence: *persistence.SmsPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(SmsEvent),

    pub fn init(persistence_ptr: *persistence.SmsPersistence) SmsService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *SmsService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *SmsService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *SmsService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduSmss(self: *SmsService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSms) {
        var repo = self.persistence.zmoduSmsRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSms(self: *SmsService, id: i64) !?model.ZmoduSms {
        var repo = self.persistence.zmoduSmsRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSms(self: *SmsService, entity: model.ZmoduSms) !model.ZmoduSms {
        var repo = self.persistence.zmoduSmsRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSms(self: *SmsService, entity: model.ZmoduSms) !void {
        var repo = self.persistence.zmoduSmsRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSms(self: *SmsService, id: i64) !void {
        var repo = self.persistence.zmoduSmsRepo();
        return try repo.delete(id);
    }

};
