//! Auto-generated models for module: order
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduOrder = struct {
    pub const sql_table_name: []const u8 = "zmodu_order";
    order_id: i64,
    order_no: []const u8,
    total_price: f64,
    order_price: f64,
    coupon_id: i64,
    coupon_money: f64,
    coupon_id_sys: ?i64,
    coupon_money_sys: ?f64,
    points_money: f64,
    points_num: f64,
    pay_price: f64,
    update_price: f64,
    fullreduce_money: ?f64,
    fullreduce_remark: ?[]const u8,
    product_reduce_money: ?f64,
    buyer_remark: ?[]const u8,
    pay_type: i64,
    pay_source: ?[]const u8,
    pay_status: i64,
    pay_time: i64,
    pay_end_time: ?i64,
    delivery_type: i64,
    extract_store_id: i64,
    extract_clerk_id: i64,
    express_price: f64,
    express_id: i64,
    express_company: []const u8,
    express_no: []const u8,
    delivery_status: i64,
    delivery_time: i64,
    receipt_status: i64,
    receipt_time: i64,
    order_status: i64,
    points_bonus: f64,
    is_settled: i64,
    transaction_id: []const u8,
    is_comment: i64,
    order_source: i64,
    user_id: i64,
    is_refund: ?i64,
    assemble_status: ?i64,
    activity_id: ?i64,
    is_agent: ?i64,
    shop_supplier_id: ?i64,
    supplier_money: ?f64,
    sys_money: ?f64,
    room_id: ?i64,
    cancel_remark: []const u8,
    virtual_auto: i64,
    virtual_content: ?[]const u8,
    balance: f64,
    online_money: f64,
    refund_money: f64,
    trade_no: []const u8,
    wx_delivery_status: i64,
    is_single: ?i64,
    task_id: []const u8,
    return_num: []const u8,
    label: []const u8,
    kd_order_num: []const u8,
    is_label: i64,
    label_print_type: i64,
    template_id: i64,
    setting_id: i64,
    address_id: i64,
    custom_form: ?[]const u8,
    delete_time: i64,
    is_delete: i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("order_id");
        try jws.write(self.order_id);
        try jws.objectField("order_no");
        try jws.write(self.order_no);
        try jws.objectField("total_price");
        try jws.write(self.total_price);
        try jws.objectField("order_price");
        try jws.write(self.order_price);
        try jws.objectField("coupon_id");
        try jws.write(self.coupon_id);
        try jws.objectField("coupon_money");
        try jws.write(self.coupon_money);
        try jws.objectField("coupon_id_sys");
        if (self.coupon_id_sys) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("coupon_money_sys");
        if (self.coupon_money_sys) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("points_money");
        try jws.write(self.points_money);
        try jws.objectField("points_num");
        try jws.write(self.points_num);
        try jws.objectField("pay_price");
        try jws.write(self.pay_price);
        try jws.objectField("update_price");
        try jws.write(self.update_price);
        try jws.objectField("fullreduce_money");
        if (self.fullreduce_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("fullreduce_remark");
        if (self.fullreduce_remark) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("product_reduce_money");
        if (self.product_reduce_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("buyer_remark");
        if (self.buyer_remark) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("pay_type");
        try jws.write(self.pay_type);
        try jws.objectField("pay_source");
        if (self.pay_source) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("pay_status");
        try jws.write(self.pay_status);
        try jws.objectField("pay_time");
        try jws.write(self.pay_time);
        try jws.objectField("pay_end_time");
        if (self.pay_end_time) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("delivery_type");
        try jws.write(self.delivery_type);
        try jws.objectField("extract_store_id");
        try jws.write(self.extract_store_id);
        try jws.objectField("extract_clerk_id");
        try jws.write(self.extract_clerk_id);
        try jws.objectField("express_price");
        try jws.write(self.express_price);
        try jws.objectField("express_id");
        try jws.write(self.express_id);
        try jws.objectField("express_company");
        try jws.write(self.express_company);
        try jws.objectField("express_no");
        try jws.write(self.express_no);
        try jws.objectField("delivery_status");
        try jws.write(self.delivery_status);
        try jws.objectField("delivery_time");
        try jws.write(self.delivery_time);
        try jws.objectField("receipt_status");
        try jws.write(self.receipt_status);
        try jws.objectField("receipt_time");
        try jws.write(self.receipt_time);
        try jws.objectField("order_status");
        try jws.write(self.order_status);
        try jws.objectField("points_bonus");
        try jws.write(self.points_bonus);
        try jws.objectField("is_settled");
        try jws.write(self.is_settled);
        try jws.objectField("transaction_id");
        try jws.write(self.transaction_id);
        try jws.objectField("is_comment");
        try jws.write(self.is_comment);
        try jws.objectField("order_source");
        try jws.write(self.order_source);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("is_refund");
        if (self.is_refund) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("assemble_status");
        if (self.assemble_status) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("activity_id");
        if (self.activity_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_agent");
        if (self.is_agent) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("shop_supplier_id");
        if (self.shop_supplier_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("supplier_money");
        if (self.supplier_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("sys_money");
        if (self.sys_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("room_id");
        if (self.room_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("cancel_remark");
        try jws.write(self.cancel_remark);
        try jws.objectField("virtual_auto");
        try jws.write(self.virtual_auto);
        try jws.objectField("virtual_content");
        if (self.virtual_content) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("balance");
        try jws.write(self.balance);
        try jws.objectField("online_money");
        try jws.write(self.online_money);
        try jws.objectField("refund_money");
        try jws.write(self.refund_money);
        try jws.objectField("trade_no");
        try jws.write(self.trade_no);
        try jws.objectField("wx_delivery_status");
        try jws.write(self.wx_delivery_status);
        try jws.objectField("is_single");
        if (self.is_single) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("task_id");
        try jws.write(self.task_id);
        try jws.objectField("return_num");
        try jws.write(self.return_num);
        try jws.objectField("label");
        try jws.write(self.label);
        try jws.objectField("kd_order_num");
        try jws.write(self.kd_order_num);
        try jws.objectField("is_label");
        try jws.write(self.is_label);
        try jws.objectField("label_print_type");
        try jws.write(self.label_print_type);
        try jws.objectField("template_id");
        try jws.write(self.template_id);
        try jws.objectField("setting_id");
        try jws.write(self.setting_id);
        try jws.objectField("address_id");
        try jws.write(self.address_id);
        try jws.objectField("custom_form");
        if (self.custom_form) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("delete_time");
        try jws.write(self.delete_time);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduOrderAddress = struct {
    pub const sql_table_name: []const u8 = "zmodu_order_address";
    order_address_id: i64,
    name: []const u8,
    phone: []const u8,
    province_id: i64,
    city_id: i64,
    region_id: i64,
    detail: []const u8,
    order_id: i64,
    user_id: i64,
    app_id: i64,
    create_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("order_address_id");
        try jws.write(self.order_address_id);
        try jws.objectField("name");
        try jws.write(self.name);
        try jws.objectField("phone");
        try jws.write(self.phone);
        try jws.objectField("province_id");
        try jws.write(self.province_id);
        try jws.objectField("city_id");
        try jws.write(self.city_id);
        try jws.objectField("region_id");
        try jws.write(self.region_id);
        try jws.objectField("detail");
        try jws.write(self.detail);
        try jws.objectField("order_id");
        try jws.write(self.order_id);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.endObject();
    }
};

pub const ZmoduOrderAdvance = struct {
    pub const sql_table_name: []const u8 = "zmodu_order_advance";
    order_advance_id: i64,
    advance_product_id: i64,
    advance_product_sku_id: i64,
    user_id: i64,
    end_time: i64,
    order_no: []const u8,
    pay_price: f64,
    pay_type: i64,
    balance: f64,
    online_money: f64,
    pay_status: i64,
    pay_time: i64,
    order_status: i64,
    pay_end_time: ?i64,
    order_id: i64,
    pay_source: ?[]const u8,
    money_return: i64,
    refund_money: f64,
    reduce_money: f64,
    main_order_no: []const u8,
    is_refund: i64,
    shop_supplier_id: i64,
    transaction_id: []const u8,
    trade_no: []const u8,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("order_advance_id");
        try jws.write(self.order_advance_id);
        try jws.objectField("advance_product_id");
        try jws.write(self.advance_product_id);
        try jws.objectField("advance_product_sku_id");
        try jws.write(self.advance_product_sku_id);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("end_time");
        try jws.write(self.end_time);
        try jws.objectField("order_no");
        try jws.write(self.order_no);
        try jws.objectField("pay_price");
        try jws.write(self.pay_price);
        try jws.objectField("pay_type");
        try jws.write(self.pay_type);
        try jws.objectField("balance");
        try jws.write(self.balance);
        try jws.objectField("online_money");
        try jws.write(self.online_money);
        try jws.objectField("pay_status");
        try jws.write(self.pay_status);
        try jws.objectField("pay_time");
        try jws.write(self.pay_time);
        try jws.objectField("order_status");
        try jws.write(self.order_status);
        try jws.objectField("pay_end_time");
        if (self.pay_end_time) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("order_id");
        try jws.write(self.order_id);
        try jws.objectField("pay_source");
        if (self.pay_source) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("money_return");
        try jws.write(self.money_return);
        try jws.objectField("refund_money");
        try jws.write(self.refund_money);
        try jws.objectField("reduce_money");
        try jws.write(self.reduce_money);
        try jws.objectField("main_order_no");
        try jws.write(self.main_order_no);
        try jws.objectField("is_refund");
        try jws.write(self.is_refund);
        try jws.objectField("shop_supplier_id");
        try jws.write(self.shop_supplier_id);
        try jws.objectField("transaction_id");
        try jws.write(self.transaction_id);
        try jws.objectField("trade_no");
        try jws.write(self.trade_no);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduOrderDelivery = struct {
    pub const sql_table_name: []const u8 = "zmodu_order_delivery";
    order_delivery_id: i64,
    order_id: i64,
    express_id: i64,
    express_no: []const u8,
    task_id: []const u8,
    return_num: []const u8,
    label: []const u8,
    kd_order_num: []const u8,
    is_label: ?i64,
    label_print_type: i64,
    setting_id: ?i64,
    template_id: ?i64,
    address_id: ?i64,
    remark: ?[]const u8,
    delivery_data: ?[]const u8,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("order_delivery_id");
        try jws.write(self.order_delivery_id);
        try jws.objectField("order_id");
        try jws.write(self.order_id);
        try jws.objectField("express_id");
        try jws.write(self.express_id);
        try jws.objectField("express_no");
        try jws.write(self.express_no);
        try jws.objectField("task_id");
        try jws.write(self.task_id);
        try jws.objectField("return_num");
        try jws.write(self.return_num);
        try jws.objectField("label");
        try jws.write(self.label);
        try jws.objectField("kd_order_num");
        try jws.write(self.kd_order_num);
        try jws.objectField("is_label");
        if (self.is_label) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("label_print_type");
        try jws.write(self.label_print_type);
        try jws.objectField("setting_id");
        if (self.setting_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("template_id");
        if (self.template_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("address_id");
        if (self.address_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("remark");
        if (self.remark) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("delivery_data");
        if (self.delivery_data) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduOrderExtract = struct {
    pub const sql_table_name: []const u8 = "zmodu_order_extract";
    id: i64,
    order_id: i64,
    linkman: []const u8,
    phone: []const u8,
    user_id: i64,
    app_id: i64,
    create_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("id");
        try jws.write(self.id);
        try jws.objectField("order_id");
        try jws.write(self.order_id);
        try jws.objectField("linkman");
        try jws.write(self.linkman);
        try jws.objectField("phone");
        try jws.write(self.phone);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.endObject();
    }
};

pub const ZmoduOrderProduct = struct {
    pub const sql_table_name: []const u8 = "zmodu_order_product";
    order_product_id: i64,
    product_id: i64,
    product_name: []const u8,
    image_id: i64,
    deduct_stock_type: i64,
    spec_type: i64,
    spec_sku_id: []const u8,
    product_sku_id: i64,
    product_attr: []const u8,
    content: []const u8,
    product_no: []const u8,
    product_price: f64,
    line_price: f64,
    product_weight: f64,
    is_user_grade: i64,
    grade_ratio: i64,
    grade_product_price: f64,
    grade_total_money: f64,
    coupon_money_sys: ?f64,
    coupon_money: f64,
    points_money: f64,
    points_num: f64,
    points_bonus: f64,
    total_num: i64,
    total_price: f64,
    total_pay_price: f64,
    supplier_money: ?f64,
    sys_money: ?f64,
    fullreduce_money: ?f64,
    product_reduce_money: ?f64,
    is_agent: ?i64,
    is_ind_agent: i64,
    agent_money_type: i64,
    first_money: f64,
    second_money: f64,
    third_money: f64,
    is_comment: i64,
    order_id: i64,
    user_id: i64,
    product_source_id: i64,
    sku_source_id: ?i64,
    bill_source_id: ?i64,
    virtual_content: []const u8,
    delivery_num: i64,
    is_gift: i64,
    agent_first_money: f64,
    agent_second_money: f64,
    product_type: i64,
    card_type: i64,
    verify_num: i64,
    valid_type: i64,
    valid_day: i64,
    valid_start_time: i64,
    valid_end_time: i64,
    use_verify_num: i64,
    refund_status: i64,
    overdue_refund_status: i64,
    app_id: i64,
    create_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("order_product_id");
        try jws.write(self.order_product_id);
        try jws.objectField("product_id");
        try jws.write(self.product_id);
        try jws.objectField("product_name");
        try jws.write(self.product_name);
        try jws.objectField("image_id");
        try jws.write(self.image_id);
        try jws.objectField("deduct_stock_type");
        try jws.write(self.deduct_stock_type);
        try jws.objectField("spec_type");
        try jws.write(self.spec_type);
        try jws.objectField("spec_sku_id");
        try jws.write(self.spec_sku_id);
        try jws.objectField("product_sku_id");
        try jws.write(self.product_sku_id);
        try jws.objectField("product_attr");
        try jws.write(self.product_attr);
        try jws.objectField("content");
        try jws.write(self.content);
        try jws.objectField("product_no");
        try jws.write(self.product_no);
        try jws.objectField("product_price");
        try jws.write(self.product_price);
        try jws.objectField("line_price");
        try jws.write(self.line_price);
        try jws.objectField("product_weight");
        try jws.write(self.product_weight);
        try jws.objectField("is_user_grade");
        try jws.write(self.is_user_grade);
        try jws.objectField("grade_ratio");
        try jws.write(self.grade_ratio);
        try jws.objectField("grade_product_price");
        try jws.write(self.grade_product_price);
        try jws.objectField("grade_total_money");
        try jws.write(self.grade_total_money);
        try jws.objectField("coupon_money_sys");
        if (self.coupon_money_sys) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("coupon_money");
        try jws.write(self.coupon_money);
        try jws.objectField("points_money");
        try jws.write(self.points_money);
        try jws.objectField("points_num");
        try jws.write(self.points_num);
        try jws.objectField("points_bonus");
        try jws.write(self.points_bonus);
        try jws.objectField("total_num");
        try jws.write(self.total_num);
        try jws.objectField("total_price");
        try jws.write(self.total_price);
        try jws.objectField("total_pay_price");
        try jws.write(self.total_pay_price);
        try jws.objectField("supplier_money");
        if (self.supplier_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("sys_money");
        if (self.sys_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("fullreduce_money");
        if (self.fullreduce_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("product_reduce_money");
        if (self.product_reduce_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_agent");
        if (self.is_agent) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_ind_agent");
        try jws.write(self.is_ind_agent);
        try jws.objectField("agent_money_type");
        try jws.write(self.agent_money_type);
        try jws.objectField("first_money");
        try jws.write(self.first_money);
        try jws.objectField("second_money");
        try jws.write(self.second_money);
        try jws.objectField("third_money");
        try jws.write(self.third_money);
        try jws.objectField("is_comment");
        try jws.write(self.is_comment);
        try jws.objectField("order_id");
        try jws.write(self.order_id);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("product_source_id");
        try jws.write(self.product_source_id);
        try jws.objectField("sku_source_id");
        if (self.sku_source_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("bill_source_id");
        if (self.bill_source_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("virtual_content");
        try jws.write(self.virtual_content);
        try jws.objectField("delivery_num");
        try jws.write(self.delivery_num);
        try jws.objectField("is_gift");
        try jws.write(self.is_gift);
        try jws.objectField("agent_first_money");
        try jws.write(self.agent_first_money);
        try jws.objectField("agent_second_money");
        try jws.write(self.agent_second_money);
        try jws.objectField("product_type");
        try jws.write(self.product_type);
        try jws.objectField("card_type");
        try jws.write(self.card_type);
        try jws.objectField("verify_num");
        try jws.write(self.verify_num);
        try jws.objectField("valid_type");
        try jws.write(self.valid_type);
        try jws.objectField("valid_day");
        try jws.write(self.valid_day);
        try jws.objectField("valid_start_time");
        try jws.write(self.valid_start_time);
        try jws.objectField("valid_end_time");
        try jws.write(self.valid_end_time);
        try jws.objectField("use_verify_num");
        try jws.write(self.use_verify_num);
        try jws.objectField("refund_status");
        try jws.write(self.refund_status);
        try jws.objectField("overdue_refund_status");
        try jws.write(self.overdue_refund_status);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.endObject();
    }
};

pub const ZmoduOrderRefund = struct {
    pub const sql_table_name: []const u8 = "zmodu_order_refund";
    order_refund_id: i64,
    order_id: i64,
    order_product_id: i64,
    user_id: i64,
    type: i64,
    apply_desc: []const u8,
    is_agree: i64,
    refuse_desc: []const u8,
    refund_money: f64,
    is_user_send: i64,
    send_time: i64,
    express_id: []const u8,
    express_no: []const u8,
    is_receipt: i64,
    status: i64,
    deliver_time: i64,
    send_express_id: []const u8,
    send_express_no: []const u8,
    is_plate_send: i64,
    shop_supplier_id: ?i64,
    plate_status: i64,
    plate_desc: []const u8,
    out_refund_no: []const u8,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("order_refund_id");
        try jws.write(self.order_refund_id);
        try jws.objectField("order_id");
        try jws.write(self.order_id);
        try jws.objectField("order_product_id");
        try jws.write(self.order_product_id);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("type");
        try jws.write(self.type);
        try jws.objectField("apply_desc");
        try jws.write(self.apply_desc);
        try jws.objectField("is_agree");
        try jws.write(self.is_agree);
        try jws.objectField("refuse_desc");
        try jws.write(self.refuse_desc);
        try jws.objectField("refund_money");
        try jws.write(self.refund_money);
        try jws.objectField("is_user_send");
        try jws.write(self.is_user_send);
        try jws.objectField("send_time");
        try jws.write(self.send_time);
        try jws.objectField("express_id");
        try jws.write(self.express_id);
        try jws.objectField("express_no");
        try jws.write(self.express_no);
        try jws.objectField("is_receipt");
        try jws.write(self.is_receipt);
        try jws.objectField("status");
        try jws.write(self.status);
        try jws.objectField("deliver_time");
        try jws.write(self.deliver_time);
        try jws.objectField("send_express_id");
        try jws.write(self.send_express_id);
        try jws.objectField("send_express_no");
        try jws.write(self.send_express_no);
        try jws.objectField("is_plate_send");
        try jws.write(self.is_plate_send);
        try jws.objectField("shop_supplier_id");
        if (self.shop_supplier_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("plate_status");
        try jws.write(self.plate_status);
        try jws.objectField("plate_desc");
        try jws.write(self.plate_desc);
        try jws.objectField("out_refund_no");
        try jws.write(self.out_refund_no);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduOrderRefundAddress = struct {
    pub const sql_table_name: []const u8 = "zmodu_order_refund_address";
    id: i64,
    order_refund_id: i64,
    name: []const u8,
    phone: []const u8,
    detail: []const u8,
    app_id: i64,
    create_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("id");
        try jws.write(self.id);
        try jws.objectField("order_refund_id");
        try jws.write(self.order_refund_id);
        try jws.objectField("name");
        try jws.write(self.name);
        try jws.objectField("phone");
        try jws.write(self.phone);
        try jws.objectField("detail");
        try jws.write(self.detail);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.endObject();
    }
};

pub const ZmoduOrderRefundImage = struct {
    pub const sql_table_name: []const u8 = "zmodu_order_refund_image";
    id: i64,
    order_refund_id: i64,
    image_id: i64,
    app_id: i64,
    create_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("id");
        try jws.write(self.id);
        try jws.objectField("order_refund_id");
        try jws.write(self.order_refund_id);
        try jws.objectField("image_id");
        try jws.write(self.image_id);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.endObject();
    }
};

pub const ZmoduOrderSettled = struct {
    pub const sql_table_name: []const u8 = "zmodu_order_settled";
    settled_id: i64,
    order_id: ?i64,
    shop_supplier_id: ?i64,
    order_money: ?f64,
    pay_money: ?f64,
    express_money: ?f64,
    supplier_money: ?f64,
    real_supplier_money: ?f64,
    sys_money: ?f64,
    real_sys_money: ?f64,
    agent_total_money: ?f64,
    agent_money: ?f64,
    refund_money: ?f64,
    refund_supplier_money: ?f64,
    refund_sys_money: ?f64,
    app_id: ?i64,
    create_time: ?i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("settled_id");
        try jws.write(self.settled_id);
        try jws.objectField("order_id");
        if (self.order_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("shop_supplier_id");
        if (self.shop_supplier_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("order_money");
        if (self.order_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("pay_money");
        if (self.pay_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("express_money");
        if (self.express_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("supplier_money");
        if (self.supplier_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("real_supplier_money");
        if (self.real_supplier_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("sys_money");
        if (self.sys_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("real_sys_money");
        if (self.real_sys_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("agent_total_money");
        if (self.agent_total_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("agent_money");
        if (self.agent_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("refund_money");
        if (self.refund_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("refund_supplier_money");
        if (self.refund_supplier_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("refund_sys_money");
        if (self.refund_sys_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("app_id");
        if (self.app_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("create_time");
        if (self.create_time) |v| try jws.write(v) else try jws.write(null);
        try jws.endObject();
    }
};

pub const ZmoduOrderTrade = struct {
    pub const sql_table_name: []const u8 = "zmodu_order_trade";
    id: i64,
    out_trade_no: ?[]const u8,
    order_id: ?i64,
    create_time: ?i64,
    update_time: ?i64,
    app_id: ?i64,
    pay_status: ?i64,
    pay_time: ?i64,
    balance: f64,
    online_money: f64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("id");
        try jws.write(self.id);
        try jws.objectField("out_trade_no");
        if (self.out_trade_no) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("order_id");
        if (self.order_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("create_time");
        if (self.create_time) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("update_time");
        if (self.update_time) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("app_id");
        if (self.app_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("pay_status");
        if (self.pay_status) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("pay_time");
        if (self.pay_time) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("balance");
        try jws.write(self.balance);
        try jws.objectField("online_money");
        try jws.write(self.online_money);
        try jws.endObject();
    }
};

