//! Generated by zmodu saas — orders API (autoCrud: tenant-scoped CRUD, JWT, paged)
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const service = @import("service.zig");

pub const OrdersApi = zigmodu.http.CrudApi(model.Orders, service.OrdersService, .{});
