//! Generated by zmodu saas — orders API (ComptimeRouter, tenant-scoped, JWT)
const std = @import("std");
const http = @import("zigmodu").http;
const model = @import("model.zig");
const service = @import("service.zig");

pub const OrdersApi = struct {
    service: *service.OrdersService,

    pub const module_name = "orders";
    pub const nest = .{"orders"};
    pub const State = @This();

    pub fn init(s: *service.OrdersService) @This() {
        return .{ .service = s };
    }

    pub const routes = [_]http.RouteSpec(State){
        .{ .method = .GET, .path = "", .handler = list, .meta = .{ .auth = .jwt, .permission = "orders:read" } },
        .{ .method = .POST, .path = "", .handler = create, .meta = .{ .auth = .jwt, .permission = "orders:write" } },
        .{ .method = .GET, .path = "{id}", .handler = get, .meta = .{ .auth = .jwt, .permission = "orders:read" } },
        .{ .method = .PUT, .path = "{id}", .handler = update, .meta = .{ .auth = .jwt, .permission = "orders:write" } },
        .{ .method = .DELETE, .path = "{id}", .handler = remove, .meta = .{ .auth = .jwt, .permission = "orders:write" } },
    };

    fn tenantId(ctx: *http.Context) !i64 {
        const s = ctx.getAttr("tenant_id") orelse return error.Unauthorized;
        return std.fmt.parseInt(i64, s, 10);
    }

    fn list(ctx: *http.Context, self: *State) !void {
        const org_id = try tenantId(ctx);
        const page = ctx.queryInt(usize, "page", 1);
        const size = ctx.queryInt(usize, "size", 20);
        var items = try self.service.list(ctx.allocator, org_id, page, size);
        defer items.deinit(ctx.allocator);
        try ctx.jsonStruct(200, .{ .code = 0, .items = items.items, .total = items.items.len });
    }

    fn get(ctx: *http.Context, self: *State) !void {
        const org_id = try tenantId(ctx);
        const id = try ctx.paramInt(i64, "id");
        const entity = try self.service.get(ctx.allocator, org_id, id);
        if (entity) |e| {
            try ctx.jsonStruct(200, .{ .code = 0, .data = e });
        } else {
            try ctx.jsonStruct(404, .{ .code = 404, .msg = "not found" });
        }
    }

    fn create(ctx: *http.Context, self: *State) !void {
        const org_id = try tenantId(ctx);
        var entity = ctx.bindJson(model.Orders) catch return ctx.jsonStruct(400, .{ .code = 400, .msg = "invalid body" });
        entity.org_id = org_id;
        const id = try self.service.create(entity);
        try ctx.jsonStruct(200, .{ .code = 0, .id = id });
    }

    fn update(ctx: *http.Context, self: *State) !void {
        const org_id = try tenantId(ctx);
        const id = try ctx.paramInt(i64, "id");
        var entity = ctx.bindJson(model.Orders) catch return ctx.jsonStruct(400, .{ .code = 400, .msg = "invalid body" });
        entity.id = id;
        entity.org_id = org_id;
        try self.service.update(entity, org_id);
        try ctx.jsonStruct(200, .{ .code = 0 });
    }

    fn remove(ctx: *http.Context, self: *State) !void {
        const org_id = try tenantId(ctx);
        const id = try ctx.paramInt(i64, "id");
        try self.service.delete(org_id, id);
        try ctx.jsonStruct(200, .{ .code = 0 });
    }
};
