//! Generated by zmodu saas — orders model
const std = @import("std");

pub const Orders = struct {
    id: i64 = 0,
    org_id: i64 = 0,
    customer: []const u8 = "",
    amount: i64 = 0,
    status: []const u8 = "pending",
    notes: []const u8 = "",
    created_at: i64 = 0,
    updated_at: i64 = 0,
};
