//! Generated by zmodu saas — orders module
const zigmodu = @import("zigmodu");
pub const info = zigmodu.api.Module{
    .name = "orders",
    .description = "orders business module",
    .dependencies = &.{},
};
pub fn init() !void {}
pub fn deinit() void {}
