//! Generated by zmodu saas — orders service (CrudService event-source composition)
const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const OrdersService = struct {
    pub const module_name = "orders";
    pub const nest = .{"orders"};
    pub const impl = zigmodu.data.CrudService(model.Orders, persistence.OrdersPersistence);
    crud: impl,

    pub fn init(p: *persistence.OrdersPersistence) @This() {
        var self: @This() = .{ .crud = impl.init(p) };
        self.crud.validate = &validate;
        return self;
    }

    pub fn validate(e: model.Orders) anyerror!void {
        if (e.customer.len == 0) return error.ValidationFailed;
    }
};
