//! Auto-generated HTTP API for module: seckill
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const SeckillApi = struct {
    service: *service.SeckillService,

    pub fn init(service_ptr: *service.SeckillService) SeckillApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *SeckillApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_seckill_activitys", listZmoduSeckillActivitys, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_seckill_activitys/:id", getZmoduSeckillActivity, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_seckill_activitys", createZmoduSeckillActivity, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_seckill_activitys/:id", updateZmoduSeckillActivity, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_seckill_activitys/:id", deleteZmoduSeckillActivity, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_seckill_products", listZmoduSeckillProducts, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_seckill_products/:id", getZmoduSeckillProduct, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_seckill_products", createZmoduSeckillProduct, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_seckill_products/:id", updateZmoduSeckillProduct, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_seckill_products/:id", deleteZmoduSeckillProduct, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_seckill_product_skus", listZmoduSeckillProductSkus, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_seckill_product_skus/:id", getZmoduSeckillProductSku, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_seckill_product_skus", createZmoduSeckillProductSku, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_seckill_product_skus/:id", updateZmoduSeckillProductSku, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_seckill_product_skus/:id", deleteZmoduSeckillProductSku, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_seckill_times", listZmoduSeckillTimes, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_seckill_times/:id", getZmoduSeckillTime, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_seckill_times", createZmoduSeckillTime, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_seckill_times/:id", updateZmoduSeckillTime, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_seckill_times/:id", deleteZmoduSeckillTime, @ptrCast(@alignCast(self)));
    }

    fn listZmoduSeckillActivitys(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[seckill] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[seckill] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduSeckillActivitys(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduSeckillActivity(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[seckill] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[seckill] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduSeckillActivity(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduSeckillActivity(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduSeckillActivity) catch {
            std.log.warn("[seckill] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduSeckillActivity(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduSeckillActivity(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduSeckillActivity) catch {
            std.log.warn("[seckill] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduSeckillActivity(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduSeckillActivity(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[seckill] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduSeckillActivity(id);
        try ctx.json(204, "");
    }

    fn listZmoduSeckillProducts(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[seckill] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[seckill] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduSeckillProducts(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduSeckillProduct(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[seckill] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[seckill] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduSeckillProduct(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduSeckillProduct(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduSeckillProduct) catch {
            std.log.warn("[seckill] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduSeckillProduct(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduSeckillProduct(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduSeckillProduct) catch {
            std.log.warn("[seckill] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduSeckillProduct(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduSeckillProduct(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[seckill] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduSeckillProduct(id);
        try ctx.json(204, "");
    }

    fn listZmoduSeckillProductSkus(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[seckill] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[seckill] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduSeckillProductSkus(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduSeckillProductSku(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[seckill] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[seckill] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduSeckillProductSku(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduSeckillProductSku(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduSeckillProductSku) catch {
            std.log.warn("[seckill] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduSeckillProductSku(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduSeckillProductSku(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduSeckillProductSku) catch {
            std.log.warn("[seckill] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduSeckillProductSku(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduSeckillProductSku(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[seckill] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduSeckillProductSku(id);
        try ctx.json(204, "");
    }

    fn listZmoduSeckillTimes(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[seckill] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[seckill] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduSeckillTimes(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduSeckillTime(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[seckill] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[seckill] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduSeckillTime(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduSeckillTime(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduSeckillTime) catch {
            std.log.warn("[seckill] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduSeckillTime(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduSeckillTime(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduSeckillTime) catch {
            std.log.warn("[seckill] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduSeckillTime(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduSeckillTime(ctx: *zigmodu.http_server.Context) !void {
        const self: *SeckillApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[seckill] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduSeckillTime(id);
        try ctx.json(204, "");
    }

};
