//! Auto-generated service for module: seckill
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=seckill | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const SeckillService = struct {
    persistence: *persistence.SeckillPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(SeckillEvent),

    pub fn init(persistence_ptr: *persistence.SeckillPersistence) SeckillService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *SeckillService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *SeckillService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *SeckillService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduSeckillActivitys(self: *SeckillService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSeckillActivity) {
        var repo = self.persistence.zmoduSeckillActivityRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSeckillActivity(self: *SeckillService, id: i64) !?model.ZmoduSeckillActivity {
        var repo = self.persistence.zmoduSeckillActivityRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSeckillActivity(self: *SeckillService, entity: model.ZmoduSeckillActivity) !model.ZmoduSeckillActivity {
        var repo = self.persistence.zmoduSeckillActivityRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSeckillActivity(self: *SeckillService, entity: model.ZmoduSeckillActivity) !void {
        var repo = self.persistence.zmoduSeckillActivityRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSeckillActivity(self: *SeckillService, id: i64) !void {
        var repo = self.persistence.zmoduSeckillActivityRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSeckillProducts(self: *SeckillService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSeckillProduct) {
        var repo = self.persistence.zmoduSeckillProductRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSeckillProduct(self: *SeckillService, id: i64) !?model.ZmoduSeckillProduct {
        var repo = self.persistence.zmoduSeckillProductRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSeckillProduct(self: *SeckillService, entity: model.ZmoduSeckillProduct) !model.ZmoduSeckillProduct {
        var repo = self.persistence.zmoduSeckillProductRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSeckillProduct(self: *SeckillService, entity: model.ZmoduSeckillProduct) !void {
        var repo = self.persistence.zmoduSeckillProductRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSeckillProduct(self: *SeckillService, id: i64) !void {
        var repo = self.persistence.zmoduSeckillProductRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSeckillProductSkus(self: *SeckillService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSeckillProductSku) {
        var repo = self.persistence.zmoduSeckillProductSkuRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSeckillProductSku(self: *SeckillService, id: i64) !?model.ZmoduSeckillProductSku {
        var repo = self.persistence.zmoduSeckillProductSkuRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSeckillProductSku(self: *SeckillService, entity: model.ZmoduSeckillProductSku) !model.ZmoduSeckillProductSku {
        var repo = self.persistence.zmoduSeckillProductSkuRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSeckillProductSku(self: *SeckillService, entity: model.ZmoduSeckillProductSku) !void {
        var repo = self.persistence.zmoduSeckillProductSkuRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSeckillProductSku(self: *SeckillService, id: i64) !void {
        var repo = self.persistence.zmoduSeckillProductSkuRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduSeckillTimes(self: *SeckillService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduSeckillTime) {
        var repo = self.persistence.zmoduSeckillTimeRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduSeckillTime(self: *SeckillService, id: i64) !?model.ZmoduSeckillTime {
        var repo = self.persistence.zmoduSeckillTimeRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduSeckillTime(self: *SeckillService, entity: model.ZmoduSeckillTime) !model.ZmoduSeckillTime {
        var repo = self.persistence.zmoduSeckillTimeRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduSeckillTime(self: *SeckillService, entity: model.ZmoduSeckillTime) !void {
        var repo = self.persistence.zmoduSeckillTimeRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduSeckillTime(self: *SeckillService, id: i64) !void {
        var repo = self.persistence.zmoduSeckillTimeRepo();
        return try repo.delete(id);
    }

};
