//! Web4 HTTP middleware: wire x402 payment gating and did:key authentication
//! into the framework's middleware chain.
//!
//!   - `x402Middleware` — routes without a valid payment proof get a 402
//!     (invoice generated by `on_invoice`), invalid proofs get 403; the
//!     default verifier is fail-closed (never accepts).
//!   - `didAuthMiddleware` — verifies a did:key signature from headers and
//!     writes `did` / `user_id` attrs for downstream handlers.

const std = @import("std");
const api = @import("../api/Server.zig");
const x402_mod = @import("x402.zig");
const x402_store_mod = @import("x402_store.zig");
const did_mod = @import("did.zig");
const challenge_mod = @import("challenge.zig");
const security_mod = @import("../security/AppSecurity.zig");

/// Config for `x402Middleware`. `verifier` must be the production payment
/// verifier (on-chain check, allow-list); the helper stays fail-closed when
/// the verifier rejects. `on_invoice` builds the 402 invoice per request
/// (route-based pricing); when absent a generic invoice is returned.
pub const X402Config = struct {
    verifier: x402_mod.PaymentVerifier = x402_mod.verifyPaymentReject,
    on_invoice: ?*const fn (*api.Context, std.mem.Allocator) anyerror!x402_mod.Invoice = null,
    /// When set, only paths starting with this prefix are gated (allows
    /// per-route protection with global middleware).
    path_prefix: ?[]const u8 = null,
    invoice_id: []const u8 = "web4-access",
    payee_did: []const u8 = "did:key:z6Mk-placeholder",
    amount: u64 = 1000000,
    currency: x402_mod.Currency = .usdc,
    description: []const u8 = "Web4 API access",
    /// When set, invoices are persisted and proofs are redeemed exactly once
    /// (idempotent anti-replay); otherwise the `verifier` callback is used.
    store: ?*x402_store_mod.X402Store = null,
};

/// x402 payment gate: no proof → 402 + invoice; invalid proof → 403; valid →
/// downstream handler.
pub fn x402Middleware(cfg: *X402Config) api.Middleware {
    return .{
        .func = struct {
            fn mw(ctx: *api.Context, next: api.HandlerFn, userdata: ?*anyopaque) anyerror!void {
                const c: *X402Config = @ptrCast(@alignCast(userdata.?));
                if (c.path_prefix) |p| {
                    if (!std.mem.startsWith(u8, ctx.path, p)) {
                        try next(ctx);
                        return;
                    }
                }
                if (ctx.header("x402-tx-hash")) |tx| {
                    const invoice_id = ctx.header("x402-invoice-id") orelse {
                        try ctx.sendError(402, "missing invoice id");
                        return;
                    };
                    if (c.store) |st| {
                        switch (try st.redeem(invoice_id, tx)) {
                            .redeemed => {
                                try ctx.setAttr("x402_paid", "true");
                                try next(ctx);
                                return;
                            },
                            .already_used, .not_found, .expired => {
                                try ctx.sendError(410, "invoice not redeemable");
                                return;
                            },
                        }
                    }
                    const proof = x402_mod.PaymentProof{
                        .tx_hash = try ctx.allocator.dupe(u8, tx),
                        .invoice_id = try ctx.allocator.dupe(u8, invoice_id),
                    };
                    defer {
                        ctx.allocator.free(proof.tx_hash);
                        ctx.allocator.free(proof.invoice_id);
                    }
                    if (x402_mod.verifyWith(c.verifier, proof)) {
                        try ctx.setAttr("x402_paid", "true");
                        try next(ctx);
                        return;
                    }
                    try ctx.sendError(403, "invalid payment proof");
                    return;
                }
                const invoice = if (c.on_invoice) |f|
                    try f(ctx, ctx.allocator)
                else blk: {
                    var id_buf: [64]u8 = undefined;
                    const id = try std.fmt.bufPrint(&id_buf, "{s}-{d}", .{ c.invoice_id, @import("../core/Time.zig").monotonicNowMilliseconds() });
                    break :blk x402_mod.Invoice{
                        .id = id,
                        .payee_did = c.payee_did,
                        .amount = c.amount,
                        .currency = c.currency,
                        .deadline = @import("../core/Time.zig").monotonicNowSeconds() + 3600,
                        .description = c.description,
                    };
                };
                if (c.store) |st| try st.create(invoice);
                try x402_mod.writePaymentRequired(ctx, ctx.allocator, invoice);
            }
        }.mw,
        .user_data = cfg,
    };
}

/// Config for `didAuthMiddleware`.
pub const DidAuthConfig = struct {
    /// Headers carrying the DID, message and base64 signature.
    did_header: []const u8 = "x-did",
    message_header: []const u8 = "x-did-message",
    signature_header: []const u8 = "x-did-signature",
    /// When set, only paths starting with this prefix require DID auth.
    path_prefix: ?[]const u8 = null,
    /// When set, `x-did-message` must be a challenge issued by the store and
    /// is consumed after one successful verification (anti-replay).
    challenge_store: ?*challenge_mod.ChallengeStore = null,
    /// When set, a JWT for the authenticated DID is issued and returned in the
    /// `x-did-token` response header — so the client can continue on the
    /// framework's JWT middleware chain.
    jwt_issuer: ?*security_mod.AppSecurity = null,
};

/// did:key authentication: verifies a signature over `message`; on success
/// writes `did` and `user_id` attrs. Missing/invalid credentials → 401.
pub fn didAuthMiddleware(cfg: *DidAuthConfig) api.Middleware {
    return .{
        .func = struct {
            fn mw(ctx: *api.Context, next: api.HandlerFn, userdata: ?*anyopaque) anyerror!void {
                const c: *DidAuthConfig = @ptrCast(@alignCast(userdata.?));
                if (c.path_prefix) |p| {
                    if (!std.mem.startsWith(u8, ctx.path, p)) {
                        try next(ctx);
                        return;
                    }
                }
                const did = ctx.header(c.did_header) orelse {
                    try ctx.sendError(401, "missing DID");
                    return;
                };
                const message = ctx.header(c.message_header) orelse {
                    try ctx.sendError(401, "missing message");
                    return;
                };
                if (c.challenge_store) |cs| {
                    if (!cs.verifyAndConsume(ctx.allocator, did, message)) {
                        try ctx.sendError(401, "invalid or expired challenge");
                        return;
                    }
                }
                const sig_b64 = ctx.header(c.signature_header) orelse {
                    try ctx.sendError(401, "missing signature");
                    return;
                };
                var key = did_mod.resolve(ctx.allocator, did) catch {
                    try ctx.sendError(401, "unresolvable DID");
                    return;
                };
                defer ctx.allocator.free(key.did);
                const dec = std.base64.standard.Decoder;
                const sig_len = dec.calcSizeForSlice(sig_b64) catch {
                    try ctx.sendError(401, "invalid signature encoding");
                    return;
                };
                const signature = try ctx.allocator.alloc(u8, sig_len);
                defer ctx.allocator.free(signature);
                dec.decode(signature, sig_b64) catch {
                    try ctx.sendError(401, "invalid signature encoding");
                    return;
                };
                if (!try key.verify(message, signature)) {
                    try ctx.sendError(401, "invalid signature");
                    return;
                }
                try ctx.setAttr("did", did);
                try ctx.setAttr("user_id", did);
                if (c.jwt_issuer) |sec| {
                    const token = try sec.generateToken(did, &.{});
                    defer ctx.allocator.free(token);
                    try ctx.setHeader("x-did-token", token);
                }
                try next(ctx);
            }
        }.mw,
        .user_data = cfg,
    };
}

test "x402Middleware gates unauthenticated requests with 402" {
    const allocator = std.testing.allocator;
    var cfg = X402Config{};
    const mw = x402Middleware(&cfg);
    var ctx = try api.Context.init(allocator, .GET, "/api/paid");
    defer ctx.deinit();
    try mw.func(&ctx, struct {
        fn h(_: *api.Context) anyerror!void {}
    }.h, mw.user_data);
    try std.testing.expectEqual(@as(u16, 402), ctx.status_code);
    try std.testing.expect(ctx.responded);
}

test "x402Middleware allows valid proofs" {
    const allocator = std.testing.allocator;
    var cfg = X402Config{ .verifier = x402_mod.verifyPaymentAllowAll };
    const mw = x402Middleware(&cfg);
    var ctx = try api.Context.init(allocator, .GET, "/api/paid");
    defer ctx.deinit();
    try ctx.headers.put(try allocator.dupe(u8, "x402-tx-hash"), try allocator.dupe(u8, "0xabc"));
    try ctx.headers.put(try allocator.dupe(u8, "x402-invoice-id"), try allocator.dupe(u8, "inv-1"));
    const State = struct {
        var reached = false;
    };
    try mw.func(&ctx, struct {
        fn h(_: *api.Context) anyerror!void {
            State.reached = true;
        }
    }.h, mw.user_data);
    try std.testing.expect(State.reached);
    try std.testing.expectEqual(@as(u16, 200), ctx.status_code);
    try std.testing.expect(!ctx.responded);
}

test "didAuthMiddleware with challenge store rejects replayed challenges" {
    const allocator = std.testing.allocator;
    var store = challenge_mod.ChallengeStore.init(allocator, std.testing.io);
    defer store.deinit();
    var cfg = DidAuthConfig{ .challenge_store = &store };
    const mw = didAuthMiddleware(&cfg);

    var key = try did_mod.DidKey.generate(allocator, std.testing.io);
    defer allocator.free(key.did);
    const challenge = try store.issue(allocator, key.did);
    defer allocator.free(challenge);
    const sig = try key.sign(allocator, challenge);
    defer allocator.free(sig);
    const enc = std.base64.standard.Encoder;
    const b64 = try allocator.alloc(u8, enc.calcSize(sig.len));
    defer allocator.free(b64);
    _ = enc.encode(b64, sig);

    const State = struct {
        var reached: usize = 0;
    };
    const Handler = struct {
        fn h(_: *api.Context) anyerror!void {
            State.reached += 1;
        }
    };

    var ctx1 = try api.Context.init(allocator, .GET, "/api/identity");
    defer ctx1.deinit();
    try ctx1.headers.put(try allocator.dupe(u8, "x-did"), try allocator.dupe(u8, key.did));
    try ctx1.headers.put(try allocator.dupe(u8, "x-did-message"), try allocator.dupe(u8, challenge));
    try ctx1.headers.put(try allocator.dupe(u8, "x-did-signature"), try allocator.dupe(u8, b64));
    try mw.func(&ctx1, Handler.h, mw.user_data);
    try std.testing.expectEqual(@as(usize, 1), State.reached);

    // Replay of the same challenge must fail (already consumed).
    var ctx2 = try api.Context.init(allocator, .GET, "/api/identity");
    defer ctx2.deinit();
    try ctx2.headers.put(try allocator.dupe(u8, "x-did"), try allocator.dupe(u8, key.did));
    try ctx2.headers.put(try allocator.dupe(u8, "x-did-message"), try allocator.dupe(u8, challenge));
    try ctx2.headers.put(try allocator.dupe(u8, "x-did-signature"), try allocator.dupe(u8, b64));
    try mw.func(&ctx2, Handler.h, mw.user_data);
    try std.testing.expectEqual(@as(usize, 1), State.reached);
    try std.testing.expectEqual(@as(u16, 401), ctx2.status_code);
}
