//! Auto-generated models for module: buy
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduBuyActivity = struct {
    pub const sql_table_name: []const u8 = "zmodu_buy_activity";
    buy_id: i64,
    name: []const u8,
    product_ids: ?[]const u8,
    sort: ?i64,
    start_time: i64,
    end_time: i64,
    status: i64,
    audit_status: i64,
    send_type: i64,
    max_times: i64,
    shop_supplier_id: ?i64,
    is_delete: i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("buy_id");
        try jws.write(self.buy_id);
        try jws.objectField("name");
        try jws.write(self.name);
        try jws.objectField("product_ids");
        if (self.product_ids) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("sort");
        if (self.sort) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("start_time");
        try jws.write(self.start_time);
        try jws.objectField("end_time");
        try jws.write(self.end_time);
        try jws.objectField("status");
        try jws.write(self.status);
        try jws.objectField("audit_status");
        try jws.write(self.audit_status);
        try jws.objectField("send_type");
        try jws.write(self.send_type);
        try jws.objectField("max_times");
        try jws.write(self.max_times);
        try jws.objectField("shop_supplier_id");
        if (self.shop_supplier_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduBuyActivityProduct = struct {
    pub const sql_table_name: []const u8 = "zmodu_buy_activity_product";
    buy_product_id: i64,
    buy_id: i64,
    product_name: []const u8,
    product_id: i64,
    product_num: i64,
    shop_supplier_id: ?i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("buy_product_id");
        try jws.write(self.buy_product_id);
        try jws.objectField("buy_id");
        try jws.write(self.buy_id);
        try jws.objectField("product_name");
        try jws.write(self.product_name);
        try jws.objectField("product_id");
        try jws.write(self.product_id);
        try jws.objectField("product_num");
        try jws.write(self.product_num);
        try jws.objectField("shop_supplier_id");
        if (self.shop_supplier_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

