//! Auto-generated ORM persistence for module: buy
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const BuyPersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) BuyPersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduBuyActivityRepo(self: *BuyPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduBuyActivity) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduBuyActivityProductRepo(self: *BuyPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduBuyActivityProduct) {
        return .{ .orm = &self.orm };
    }

};
