//! Auto-generated service for module: buy
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=buy | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const BuyService = struct {
    persistence: *persistence.BuyPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(BuyEvent),

    pub fn init(persistence_ptr: *persistence.BuyPersistence) BuyService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *BuyService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *BuyService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *BuyService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduBuyActivitys(self: *BuyService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduBuyActivity) {
        var repo = self.persistence.zmoduBuyActivityRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduBuyActivity(self: *BuyService, id: i64) !?model.ZmoduBuyActivity {
        var repo = self.persistence.zmoduBuyActivityRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduBuyActivity(self: *BuyService, entity: model.ZmoduBuyActivity) !model.ZmoduBuyActivity {
        var repo = self.persistence.zmoduBuyActivityRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduBuyActivity(self: *BuyService, entity: model.ZmoduBuyActivity) !void {
        var repo = self.persistence.zmoduBuyActivityRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduBuyActivity(self: *BuyService, id: i64) !void {
        var repo = self.persistence.zmoduBuyActivityRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduBuyActivityProducts(self: *BuyService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduBuyActivityProduct) {
        var repo = self.persistence.zmoduBuyActivityProductRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduBuyActivityProduct(self: *BuyService, id: i64) !?model.ZmoduBuyActivityProduct {
        var repo = self.persistence.zmoduBuyActivityProductRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduBuyActivityProduct(self: *BuyService, entity: model.ZmoduBuyActivityProduct) !model.ZmoduBuyActivityProduct {
        var repo = self.persistence.zmoduBuyActivityProductRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduBuyActivityProduct(self: *BuyService, entity: model.ZmoduBuyActivityProduct) !void {
        var repo = self.persistence.zmoduBuyActivityProductRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduBuyActivityProduct(self: *BuyService, id: i64) !void {
        var repo = self.persistence.zmoduBuyActivityProductRepo();
        return try repo.delete(id);
    }

};
