//! Auto-generated HTTP API for module: live
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const LiveApi = struct {
    service: *service.LiveService,

    pub fn init(service_ptr: *service.LiveService) LiveApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *LiveApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_live_gifts", listZmoduLiveGifts, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_gifts/:id", getZmoduLiveGift, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_live_gifts", createZmoduLiveGift, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_live_gifts/:id", updateZmoduLiveGift, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_live_gifts/:id", deleteZmoduLiveGift, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_plans", listZmoduLivePlans, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_plans/:id", getZmoduLivePlan, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_live_plans", createZmoduLivePlan, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_live_plans/:id", updateZmoduLivePlan, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_live_plans/:id", deleteZmoduLivePlan, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_plan_orders", listZmoduLivePlanOrders, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_plan_orders/:id", getZmoduLivePlanOrder, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_live_plan_orders", createZmoduLivePlanOrder, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_live_plan_orders/:id", updateZmoduLivePlanOrder, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_live_plan_orders/:id", deleteZmoduLivePlanOrder, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_products", listZmoduLiveProducts, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_products/:id", getZmoduLiveProduct, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_live_products", createZmoduLiveProduct, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_live_products/:id", updateZmoduLiveProduct, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_live_products/:id", deleteZmoduLiveProduct, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_rooms", listZmoduLiveRooms, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_rooms/:id", getZmoduLiveRoom, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_live_rooms", createZmoduLiveRoom, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_live_rooms/:id", updateZmoduLiveRoom, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_live_rooms/:id", deleteZmoduLiveRoom, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_room_gifts", listZmoduLiveRoomGifts, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_room_gifts/:id", getZmoduLiveRoomGift, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_live_room_gifts", createZmoduLiveRoomGift, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_live_room_gifts/:id", updateZmoduLiveRoomGift, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_live_room_gifts/:id", deleteZmoduLiveRoomGift, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_user_gifts", listZmoduLiveUserGifts, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_live_user_gifts/:id", getZmoduLiveUserGift, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_live_user_gifts", createZmoduLiveUserGift, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_live_user_gifts/:id", updateZmoduLiveUserGift, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_live_user_gifts/:id", deleteZmoduLiveUserGift, @ptrCast(@alignCast(self)));
    }

    fn listZmoduLiveGifts(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[live] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[live] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduLiveGifts(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduLiveGift(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[live] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduLiveGift(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduLiveGift(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLiveGift) catch {
            std.log.warn("[live] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduLiveGift(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduLiveGift(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLiveGift) catch {
            std.log.warn("[live] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduLiveGift(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduLiveGift(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduLiveGift(id);
        try ctx.json(204, "");
    }

    fn listZmoduLivePlans(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[live] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[live] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduLivePlans(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduLivePlan(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[live] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduLivePlan(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduLivePlan(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLivePlan) catch {
            std.log.warn("[live] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduLivePlan(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduLivePlan(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLivePlan) catch {
            std.log.warn("[live] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduLivePlan(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduLivePlan(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduLivePlan(id);
        try ctx.json(204, "");
    }

    fn listZmoduLivePlanOrders(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[live] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[live] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduLivePlanOrders(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduLivePlanOrder(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[live] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduLivePlanOrder(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduLivePlanOrder(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLivePlanOrder) catch {
            std.log.warn("[live] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduLivePlanOrder(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduLivePlanOrder(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLivePlanOrder) catch {
            std.log.warn("[live] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduLivePlanOrder(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduLivePlanOrder(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduLivePlanOrder(id);
        try ctx.json(204, "");
    }

    fn listZmoduLiveProducts(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[live] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[live] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduLiveProducts(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduLiveProduct(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[live] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduLiveProduct(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduLiveProduct(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLiveProduct) catch {
            std.log.warn("[live] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduLiveProduct(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduLiveProduct(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLiveProduct) catch {
            std.log.warn("[live] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduLiveProduct(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduLiveProduct(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduLiveProduct(id);
        try ctx.json(204, "");
    }

    fn listZmoduLiveRooms(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[live] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[live] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduLiveRooms(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduLiveRoom(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[live] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduLiveRoom(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduLiveRoom(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLiveRoom) catch {
            std.log.warn("[live] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduLiveRoom(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduLiveRoom(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLiveRoom) catch {
            std.log.warn("[live] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduLiveRoom(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduLiveRoom(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduLiveRoom(id);
        try ctx.json(204, "");
    }

    fn listZmoduLiveRoomGifts(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[live] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[live] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduLiveRoomGifts(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduLiveRoomGift(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[live] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduLiveRoomGift(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduLiveRoomGift(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLiveRoomGift) catch {
            std.log.warn("[live] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduLiveRoomGift(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduLiveRoomGift(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLiveRoomGift) catch {
            std.log.warn("[live] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduLiveRoomGift(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduLiveRoomGift(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduLiveRoomGift(id);
        try ctx.json(204, "");
    }

    fn listZmoduLiveUserGifts(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[live] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[live] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduLiveUserGifts(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduLiveUserGift(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[live] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduLiveUserGift(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduLiveUserGift(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLiveUserGift) catch {
            std.log.warn("[live] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduLiveUserGift(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduLiveUserGift(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduLiveUserGift) catch {
            std.log.warn("[live] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduLiveUserGift(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduLiveUserGift(ctx: *zigmodu.http_server.Context) !void {
        const self: *LiveApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[live] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduLiveUserGift(id);
        try ctx.json(204, "");
    }

};
