//! Auto-generated ORM persistence for module: live
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const LivePersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) LivePersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduLiveGiftRepo(self: *LivePersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduLiveGift) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduLivePlanRepo(self: *LivePersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduLivePlan) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduLivePlanOrderRepo(self: *LivePersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduLivePlanOrder) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduLiveProductRepo(self: *LivePersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduLiveProduct) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduLiveRoomRepo(self: *LivePersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduLiveRoom) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduLiveRoomGiftRepo(self: *LivePersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduLiveRoomGift) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduLiveUserGiftRepo(self: *LivePersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduLiveUserGift) {
        return .{ .orm = &self.orm };
    }

};
