//! Auto-generated service for module: page
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=page | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const PageService = struct {
    persistence: *persistence.PagePersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(PageEvent),

    pub fn init(persistence_ptr: *persistence.PagePersistence) PageService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *PageService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *PageService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *PageService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduPages(self: *PageService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduPage) {
        var repo = self.persistence.zmoduPageRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduPage(self: *PageService, id: i64) !?model.ZmoduPage {
        var repo = self.persistence.zmoduPageRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduPage(self: *PageService, entity: model.ZmoduPage) !model.ZmoduPage {
        var repo = self.persistence.zmoduPageRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduPage(self: *PageService, entity: model.ZmoduPage) !void {
        var repo = self.persistence.zmoduPageRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduPage(self: *PageService, id: i64) !void {
        var repo = self.persistence.zmoduPageRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduPageCategorys(self: *PageService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduPageCategory) {
        var repo = self.persistence.zmoduPageCategoryRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduPageCategory(self: *PageService, id: i64) !?model.ZmoduPageCategory {
        var repo = self.persistence.zmoduPageCategoryRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduPageCategory(self: *PageService, entity: model.ZmoduPageCategory) !model.ZmoduPageCategory {
        var repo = self.persistence.zmoduPageCategoryRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduPageCategory(self: *PageService, entity: model.ZmoduPageCategory) !void {
        var repo = self.persistence.zmoduPageCategoryRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduPageCategory(self: *PageService, id: i64) !void {
        var repo = self.persistence.zmoduPageCategoryRepo();
        return try repo.delete(id);
    }

};
