//! Auto-generated service for module: express
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=express | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const ExpressService = struct {
    persistence: *persistence.ExpressPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(ExpressEvent),

    pub fn init(persistence_ptr: *persistence.ExpressPersistence) ExpressService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *ExpressService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *ExpressService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *ExpressService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduExpresss(self: *ExpressService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduExpress) {
        var repo = self.persistence.zmoduExpressRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduExpress(self: *ExpressService, id: i64) !?model.ZmoduExpress {
        var repo = self.persistence.zmoduExpressRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduExpress(self: *ExpressService, entity: model.ZmoduExpress) !model.ZmoduExpress {
        var repo = self.persistence.zmoduExpressRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduExpress(self: *ExpressService, entity: model.ZmoduExpress) !void {
        var repo = self.persistence.zmoduExpressRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduExpress(self: *ExpressService, id: i64) !void {
        var repo = self.persistence.zmoduExpressRepo();
        return try repo.delete(id);
    }

};
