//! Auto-generated service for module: version
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=version | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const VersionService = struct {
    persistence: *persistence.VersionPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(VersionEvent),

    pub fn init(persistence_ptr: *persistence.VersionPersistence) VersionService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *VersionService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *VersionService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *VersionService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduVersions(self: *VersionService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduVersion) {
        var repo = self.persistence.zmoduVersionRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduVersion(self: *VersionService, id: i64) !?model.ZmoduVersion {
        var repo = self.persistence.zmoduVersionRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduVersion(self: *VersionService, entity: model.ZmoduVersion) !model.ZmoduVersion {
        var repo = self.persistence.zmoduVersionRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduVersion(self: *VersionService, entity: model.ZmoduVersion) !void {
        var repo = self.persistence.zmoduVersionRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduVersion(self: *VersionService, id: i64) !void {
        var repo = self.persistence.zmoduVersionRepo();
        return try repo.delete(id);
    }

};
