//! Auto-generated HTTP API for module: article
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const ArticleApi = struct {
    service: *service.ArticleService,

    pub fn init(service_ptr: *service.ArticleService) ArticleApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *ArticleApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_articles", listZmoduArticles, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_articles/:id", getZmoduArticle, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_articles", createZmoduArticle, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_articles/:id", updateZmoduArticle, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_articles/:id", deleteZmoduArticle, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_article_categorys", listZmoduArticleCategorys, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_article_categorys/:id", getZmoduArticleCategory, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_article_categorys", createZmoduArticleCategory, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_article_categorys/:id", updateZmoduArticleCategory, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_article_categorys/:id", deleteZmoduArticleCategory, @ptrCast(@alignCast(self)));
    }

    fn listZmoduArticles(ctx: *zigmodu.http_server.Context) !void {
        const self: *ArticleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[article] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[article] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduArticles(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduArticle(ctx: *zigmodu.http_server.Context) !void {
        const self: *ArticleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[article] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[article] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduArticle(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduArticle(ctx: *zigmodu.http_server.Context) !void {
        const self: *ArticleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduArticle) catch {
            std.log.warn("[article] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduArticle(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduArticle(ctx: *zigmodu.http_server.Context) !void {
        const self: *ArticleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduArticle) catch {
            std.log.warn("[article] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduArticle(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduArticle(ctx: *zigmodu.http_server.Context) !void {
        const self: *ArticleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[article] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduArticle(id);
        try ctx.json(204, "");
    }

    fn listZmoduArticleCategorys(ctx: *zigmodu.http_server.Context) !void {
        const self: *ArticleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[article] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[article] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduArticleCategorys(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduArticleCategory(ctx: *zigmodu.http_server.Context) !void {
        const self: *ArticleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[article] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[article] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduArticleCategory(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduArticleCategory(ctx: *zigmodu.http_server.Context) !void {
        const self: *ArticleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduArticleCategory) catch {
            std.log.warn("[article] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduArticleCategory(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduArticleCategory(ctx: *zigmodu.http_server.Context) !void {
        const self: *ArticleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduArticleCategory) catch {
            std.log.warn("[article] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduArticleCategory(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduArticleCategory(ctx: *zigmodu.http_server.Context) !void {
        const self: *ArticleApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[article] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduArticleCategory(id);
        try ctx.json(204, "");
    }

};
