//! Auto-generated models for module: article
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduArticle = struct {
    pub const sql_table_name: []const u8 = "zmodu_article";
    article_id: i64,
    article_title: []const u8,
    show_type: i64,
    category_id: i64,
    image_id: i64,
    article_content: []const u8,
    article_sort: i64,
    article_status: i64,
    virtual_views: i64,
    actual_views: i64,
    is_delete: i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,
    dec: []const u8,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("article_id");
        try jws.write(self.article_id);
        try jws.objectField("article_title");
        try jws.write(self.article_title);
        try jws.objectField("show_type");
        try jws.write(self.show_type);
        try jws.objectField("category_id");
        try jws.write(self.category_id);
        try jws.objectField("image_id");
        try jws.write(self.image_id);
        try jws.objectField("article_content");
        try jws.write(self.article_content);
        try jws.objectField("article_sort");
        try jws.write(self.article_sort);
        try jws.objectField("article_status");
        try jws.write(self.article_status);
        try jws.objectField("virtual_views");
        try jws.write(self.virtual_views);
        try jws.objectField("actual_views");
        try jws.write(self.actual_views);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.objectField("dec");
        try jws.write(self.dec);
        try jws.endObject();
    }
};

pub const ZmoduArticleCategory = struct {
    pub const sql_table_name: []const u8 = "zmodu_article_category";
    category_id: i64,
    name: []const u8,
    sort: i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("category_id");
        try jws.write(self.category_id);
        try jws.objectField("name");
        try jws.write(self.name);
        try jws.objectField("sort");
        try jws.write(self.sort);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

