//! Auto-generated ORM persistence for module: article
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const ArticlePersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) ArticlePersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduArticleRepo(self: *ArticlePersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduArticle) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduArticleCategoryRepo(self: *ArticlePersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduArticleCategory) {
        return .{ .orm = &self.orm };
    }

};
