//! Auto-generated service for module: article
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=article | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const ArticleService = struct {
    persistence: *persistence.ArticlePersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(ArticleEvent),

    pub fn init(persistence_ptr: *persistence.ArticlePersistence) ArticleService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *ArticleService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *ArticleService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *ArticleService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduArticles(self: *ArticleService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduArticle) {
        var repo = self.persistence.zmoduArticleRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduArticle(self: *ArticleService, id: i64) !?model.ZmoduArticle {
        var repo = self.persistence.zmoduArticleRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduArticle(self: *ArticleService, entity: model.ZmoduArticle) !model.ZmoduArticle {
        var repo = self.persistence.zmoduArticleRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduArticle(self: *ArticleService, entity: model.ZmoduArticle) !void {
        var repo = self.persistence.zmoduArticleRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduArticle(self: *ArticleService, id: i64) !void {
        var repo = self.persistence.zmoduArticleRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduArticleCategorys(self: *ArticleService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduArticleCategory) {
        var repo = self.persistence.zmoduArticleCategoryRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduArticleCategory(self: *ArticleService, id: i64) !?model.ZmoduArticleCategory {
        var repo = self.persistence.zmoduArticleCategoryRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduArticleCategory(self: *ArticleService, entity: model.ZmoduArticleCategory) !model.ZmoduArticleCategory {
        var repo = self.persistence.zmoduArticleCategoryRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduArticleCategory(self: *ArticleService, entity: model.ZmoduArticleCategory) !void {
        var repo = self.persistence.zmoduArticleCategoryRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduArticleCategory(self: *ArticleService, id: i64) !void {
        var repo = self.persistence.zmoduArticleCategoryRepo();
        return try repo.delete(id);
    }

};
