//! Auto-generated models for module: return
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduReturnAddress = struct {
    pub const sql_table_name: []const u8 = "zmodu_return_address";
    address_id: i64,
    name: []const u8,
    phone: []const u8,
    detail: []const u8,
    sort: i64,
    is_delete: i64,
    shop_supplier_id: i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("address_id");
        try jws.write(self.address_id);
        try jws.objectField("name");
        try jws.write(self.name);
        try jws.objectField("phone");
        try jws.write(self.phone);
        try jws.objectField("detail");
        try jws.write(self.detail);
        try jws.objectField("sort");
        try jws.write(self.sort);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("shop_supplier_id");
        try jws.write(self.shop_supplier_id);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

