const std = @import("std");
const db_link = @import("db_link.zig");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const db_opt = b.option([]const u8, "db", "SQL drivers to link: all|sqlite|postgres|mysql (comma-list)") orelse "all";
    const features = db_link.parseDb(db_opt) catch {
        @panic("invalid -Ddb= value; use all|sqlite|postgres|mysql (comma-list ok)");
    };

    const build_options = b.addOptions();
    db_link.addToOptions(build_options, features);
    const build_options_mod = build_options.createModule();

    const zigmodu_mod = b.addModule("zigmodu", .{
        .root_source_file = b.path("../../../src/root.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    zigmodu_mod.addImport("build_options", build_options_mod);
    db_link.link(zigmodu_mod, b, features);

    const exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    exe_mod.addImport("zigmodu", zigmodu_mod);

    const exe = b.addExecutable(.{
        .name = "zmsaas-backend",
        .root_module = exe_mod,
    });

    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    const run_step = b.step("run", "Run tenant-mgmt API server");
    run_step.dependOn(&run_cmd.step);

    // Module smoke tests (generated by `zmodu saas` — in-memory sqlite CRUD).
    const test_mod = b.createModule(.{
        .root_source_file = b.path("src/modules/orders/tests.zig"),
        .target = target,
        .optimize = optimize,
    });
    test_mod.addImport("zigmodu", zigmodu_mod);
    const tests = b.addTest(.{ .root_module = test_mod });
    const test_step = b.step("test", "Run module smoke tests");
    test_step.dependOn(&b.addRunArtifact(tests).step);
}
