//! Auto-generated models for module: register
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduRegisterRecord = struct {
    pub const sql_table_name: []const u8 = "zmodu_register_record";
    record_id: i64,
    user_id: i64,
    content: ?[]const u8,
    is_push: i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("record_id");
        try jws.write(self.record_id);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("content");
        if (self.content) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_push");
        try jws.write(self.is_push);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

