//! Auto-generated service for module: register
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=register | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const RegisterService = struct {
    persistence: *persistence.RegisterPersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(RegisterEvent),

    pub fn init(persistence_ptr: *persistence.RegisterPersistence) RegisterService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *RegisterService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *RegisterService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *RegisterService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduRegisterRecords(self: *RegisterService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduRegisterRecord) {
        var repo = self.persistence.zmoduRegisterRecordRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduRegisterRecord(self: *RegisterService, id: i64) !?model.ZmoduRegisterRecord {
        var repo = self.persistence.zmoduRegisterRecordRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduRegisterRecord(self: *RegisterService, entity: model.ZmoduRegisterRecord) !model.ZmoduRegisterRecord {
        var repo = self.persistence.zmoduRegisterRecordRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduRegisterRecord(self: *RegisterService, entity: model.ZmoduRegisterRecord) !void {
        var repo = self.persistence.zmoduRegisterRecordRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduRegisterRecord(self: *RegisterService, id: i64) !void {
        var repo = self.persistence.zmoduRegisterRecordRepo();
        return try repo.delete(id);
    }

};
