//! Auto-generated models for module: balance
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduBalanceOrder = struct {
    pub const sql_table_name: []const u8 = "zmodu_balance_order";
    order_id: i64,
    order_no: []const u8,
    user_id: i64,
    type: i64,
    plan_id: i64,
    pay_price: f64,
    give_money: f64,
    real_money: f64,
    pay_status: i64,
    pay_time: i64,
    transaction_id: []const u8,
    snapshot: ?[]const u8,
    pay_type: ?i64,
    pay_source: ?[]const u8,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("order_id");
        try jws.write(self.order_id);
        try jws.objectField("order_no");
        try jws.write(self.order_no);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("type");
        try jws.write(self.type);
        try jws.objectField("plan_id");
        try jws.write(self.plan_id);
        try jws.objectField("pay_price");
        try jws.write(self.pay_price);
        try jws.objectField("give_money");
        try jws.write(self.give_money);
        try jws.objectField("real_money");
        try jws.write(self.real_money);
        try jws.objectField("pay_status");
        try jws.write(self.pay_status);
        try jws.objectField("pay_time");
        try jws.write(self.pay_time);
        try jws.objectField("transaction_id");
        try jws.write(self.transaction_id);
        try jws.objectField("snapshot");
        if (self.snapshot) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("pay_type");
        if (self.pay_type) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("pay_source");
        if (self.pay_source) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduBalancePlan = struct {
    pub const sql_table_name: []const u8 = "zmodu_balance_plan";
    plan_id: i64,
    plan_name: []const u8,
    money: i64,
    give_money: i64,
    real_money: ?i64,
    sort: i64,
    is_delete: i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("plan_id");
        try jws.write(self.plan_id);
        try jws.objectField("plan_name");
        try jws.write(self.plan_name);
        try jws.objectField("money");
        try jws.write(self.money);
        try jws.objectField("give_money");
        try jws.write(self.give_money);
        try jws.objectField("real_money");
        if (self.real_money) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("sort");
        try jws.write(self.sort);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

