//! Auto-generated HTTP API for module: shop
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const ShopApi = struct {
    service: *service.ShopService,

    pub fn init(service_ptr: *service.ShopService) ShopApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *ShopApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_shop_accesss", listZmoduShopAccesss, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_accesss/:id", getZmoduShopAccess, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_shop_accesss", createZmoduShopAccess, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_shop_accesss/:id", updateZmoduShopAccess, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_shop_accesss/:id", deleteZmoduShopAccess, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_fullreduces", listZmoduShopFullreduces, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_fullreduces/:id", getZmoduShopFullreduce, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_shop_fullreduces", createZmoduShopFullreduce, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_shop_fullreduces/:id", updateZmoduShopFullreduce, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_shop_fullreduces/:id", deleteZmoduShopFullreduce, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_login_logs", listZmoduShopLoginLogs, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_login_logs/:id", getZmoduShopLoginLog, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_shop_login_logs", createZmoduShopLoginLog, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_shop_login_logs/:id", updateZmoduShopLoginLog, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_shop_login_logs/:id", deleteZmoduShopLoginLog, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_opt_logs", listZmoduShopOptLogs, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_opt_logs/:id", getZmoduShopOptLog, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_shop_opt_logs", createZmoduShopOptLog, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_shop_opt_logs/:id", updateZmoduShopOptLog, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_shop_opt_logs/:id", deleteZmoduShopOptLog, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_roles", listZmoduShopRoles, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_roles/:id", getZmoduShopRole, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_shop_roles", createZmoduShopRole, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_shop_roles/:id", updateZmoduShopRole, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_shop_roles/:id", deleteZmoduShopRole, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_role_accesss", listZmoduShopRoleAccesss, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_role_accesss/:id", getZmoduShopRoleAccess, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_shop_role_accesss", createZmoduShopRoleAccess, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_shop_role_accesss/:id", updateZmoduShopRoleAccess, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_shop_role_accesss/:id", deleteZmoduShopRoleAccess, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_users", listZmoduShopUsers, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_users/:id", getZmoduShopUser, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_shop_users", createZmoduShopUser, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_shop_users/:id", updateZmoduShopUser, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_shop_users/:id", deleteZmoduShopUser, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_user_roles", listZmoduShopUserRoles, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_shop_user_roles/:id", getZmoduShopUserRole, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_shop_user_roles", createZmoduShopUserRole, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_shop_user_roles/:id", updateZmoduShopUserRole, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_shop_user_roles/:id", deleteZmoduShopUserRole, @ptrCast(@alignCast(self)));
    }

    fn listZmoduShopAccesss(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[shop] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[shop] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduShopAccesss(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduShopAccess(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[shop] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduShopAccess(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduShopAccess(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopAccess) catch {
            std.log.warn("[shop] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduShopAccess(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduShopAccess(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopAccess) catch {
            std.log.warn("[shop] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduShopAccess(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduShopAccess(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduShopAccess(id);
        try ctx.json(204, "");
    }

    fn listZmoduShopFullreduces(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[shop] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[shop] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduShopFullreduces(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduShopFullreduce(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[shop] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduShopFullreduce(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduShopFullreduce(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopFullreduce) catch {
            std.log.warn("[shop] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduShopFullreduce(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduShopFullreduce(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopFullreduce) catch {
            std.log.warn("[shop] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduShopFullreduce(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduShopFullreduce(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduShopFullreduce(id);
        try ctx.json(204, "");
    }

    fn listZmoduShopLoginLogs(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[shop] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[shop] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduShopLoginLogs(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduShopLoginLog(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[shop] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduShopLoginLog(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduShopLoginLog(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopLoginLog) catch {
            std.log.warn("[shop] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduShopLoginLog(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduShopLoginLog(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopLoginLog) catch {
            std.log.warn("[shop] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduShopLoginLog(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduShopLoginLog(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduShopLoginLog(id);
        try ctx.json(204, "");
    }

    fn listZmoduShopOptLogs(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[shop] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[shop] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduShopOptLogs(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduShopOptLog(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[shop] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduShopOptLog(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduShopOptLog(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopOptLog) catch {
            std.log.warn("[shop] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduShopOptLog(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduShopOptLog(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopOptLog) catch {
            std.log.warn("[shop] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduShopOptLog(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduShopOptLog(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduShopOptLog(id);
        try ctx.json(204, "");
    }

    fn listZmoduShopRoles(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[shop] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[shop] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduShopRoles(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduShopRole(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[shop] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduShopRole(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduShopRole(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopRole) catch {
            std.log.warn("[shop] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduShopRole(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduShopRole(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopRole) catch {
            std.log.warn("[shop] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduShopRole(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduShopRole(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduShopRole(id);
        try ctx.json(204, "");
    }

    fn listZmoduShopRoleAccesss(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[shop] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[shop] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduShopRoleAccesss(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduShopRoleAccess(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[shop] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduShopRoleAccess(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduShopRoleAccess(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopRoleAccess) catch {
            std.log.warn("[shop] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduShopRoleAccess(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduShopRoleAccess(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopRoleAccess) catch {
            std.log.warn("[shop] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduShopRoleAccess(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduShopRoleAccess(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduShopRoleAccess(id);
        try ctx.json(204, "");
    }

    fn listZmoduShopUsers(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[shop] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[shop] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduShopUsers(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduShopUser(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[shop] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduShopUser(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduShopUser(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopUser) catch {
            std.log.warn("[shop] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduShopUser(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduShopUser(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopUser) catch {
            std.log.warn("[shop] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduShopUser(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduShopUser(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduShopUser(id);
        try ctx.json(204, "");
    }

    fn listZmoduShopUserRoles(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[shop] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[shop] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduShopUserRoles(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduShopUserRole(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[shop] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduShopUserRole(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduShopUserRole(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopUserRole) catch {
            std.log.warn("[shop] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduShopUserRole(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduShopUserRole(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduShopUserRole) catch {
            std.log.warn("[shop] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduShopUserRole(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduShopUserRole(ctx: *zigmodu.http_server.Context) !void {
        const self: *ShopApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[shop] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduShopUserRole(id);
        try ctx.json(204, "");
    }

};
