//! Auto-generated ORM persistence for module: shop
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const ShopPersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) ShopPersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduShopAccessRepo(self: *ShopPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduShopAccess) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduShopFullreduceRepo(self: *ShopPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduShopFullreduce) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduShopLoginLogRepo(self: *ShopPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduShopLoginLog) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduShopOptLogRepo(self: *ShopPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduShopOptLog) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduShopRoleRepo(self: *ShopPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduShopRole) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduShopRoleAccessRepo(self: *ShopPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduShopRoleAccess) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduShopUserRepo(self: *ShopPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduShopUser) {
        return .{ .orm = &self.orm };
    }

    pub fn zmoduShopUserRoleRepo(self: *ShopPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduShopUserRole) {
        return .{ .orm = &self.orm };
    }

};
