//! Auto-generated zent Client for module: <<MODULE_NAME>>
//! Generated by zmodu orm --backend zent
//! Do not modify manually

const std = @import("std");
const zent = @import("zent");
const schemas = @import("schema.zig");

const graph = zent.codegen.graph.buildGraph(&.{ 
