//! Auto-generated models for module: comment
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduComment = struct {
    pub const sql_table_name: []const u8 = "zmodu_comment";
    comment_id: i64,
    score: ?i64,
    express_score: i64,
    server_score: i64,
    describe_score: ?i64,
    content: []const u8,
    is_picture: i64,
    sort: i64,
    status: i64,
    user_id: i64,
    order_id: i64,
    product_id: i64,
    order_product_id: i64,
    shop_supplier_id: ?i64,
    app_id: i64,
    is_delete: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("comment_id");
        try jws.write(self.comment_id);
        try jws.objectField("score");
        if (self.score) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("express_score");
        try jws.write(self.express_score);
        try jws.objectField("server_score");
        try jws.write(self.server_score);
        try jws.objectField("describe_score");
        if (self.describe_score) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("content");
        try jws.write(self.content);
        try jws.objectField("is_picture");
        try jws.write(self.is_picture);
        try jws.objectField("sort");
        try jws.write(self.sort);
        try jws.objectField("status");
        try jws.write(self.status);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("order_id");
        try jws.write(self.order_id);
        try jws.objectField("product_id");
        try jws.write(self.product_id);
        try jws.objectField("order_product_id");
        try jws.write(self.order_product_id);
        try jws.objectField("shop_supplier_id");
        if (self.shop_supplier_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduCommentImage = struct {
    pub const sql_table_name: []const u8 = "zmodu_comment_image";
    id: i64,
    comment_id: i64,
    image_id: i64,
    app_id: i64,
    create_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("id");
        try jws.write(self.id);
        try jws.objectField("comment_id");
        try jws.write(self.comment_id);
        try jws.objectField("image_id");
        try jws.write(self.image_id);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.endObject();
    }
};

