//! Auto-generated HTTP API for module: store
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const StoreApi = struct {
    service: *service.StoreService,

    pub fn init(service_ptr: *service.StoreService) StoreApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *StoreApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_stores", listZmoduStores, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_stores/:id", getZmoduStore, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_stores", createZmoduStore, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_stores/:id", updateZmoduStore, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_stores/:id", deleteZmoduStore, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_store_clerks", listZmoduStoreClerks, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_store_clerks/:id", getZmoduStoreClerk, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_store_clerks", createZmoduStoreClerk, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_store_clerks/:id", updateZmoduStoreClerk, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_store_clerks/:id", deleteZmoduStoreClerk, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_store_orders", listZmoduStoreOrders, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_store_orders/:id", getZmoduStoreOrder, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_store_orders", createZmoduStoreOrder, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_store_orders/:id", updateZmoduStoreOrder, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_store_orders/:id", deleteZmoduStoreOrder, @ptrCast(@alignCast(self)));
    }

    fn listZmoduStores(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[store] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[store] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduStores(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduStore(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[store] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[store] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduStore(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduStore(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduStore) catch {
            std.log.warn("[store] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduStore(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduStore(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduStore) catch {
            std.log.warn("[store] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduStore(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduStore(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[store] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduStore(id);
        try ctx.json(204, "");
    }

    fn listZmoduStoreClerks(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[store] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[store] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduStoreClerks(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduStoreClerk(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[store] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[store] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduStoreClerk(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduStoreClerk(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduStoreClerk) catch {
            std.log.warn("[store] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduStoreClerk(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduStoreClerk(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduStoreClerk) catch {
            std.log.warn("[store] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduStoreClerk(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduStoreClerk(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[store] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduStoreClerk(id);
        try ctx.json(204, "");
    }

    fn listZmoduStoreOrders(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[store] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[store] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduStoreOrders(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduStoreOrder(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[store] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[store] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduStoreOrder(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduStoreOrder(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduStoreOrder) catch {
            std.log.warn("[store] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduStoreOrder(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduStoreOrder(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduStoreOrder) catch {
            std.log.warn("[store] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduStoreOrder(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduStoreOrder(ctx: *zigmodu.http_server.Context) !void {
        const self: *StoreApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[store] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduStoreOrder(id);
        try ctx.json(204, "");
    }

};
