//! Auto-generated models for module: store
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//! Do not edit generated files by hand; change SQL and re-run `zmodu orm`.

const std = @import("std");

pub const ZmoduStore = struct {
    pub const sql_table_name: []const u8 = "zmodu_store";
    store_id: i64,
    store_name: []const u8,
    logo_image_id: i64,
    linkman: []const u8,
    phone: []const u8,
    shop_hours: []const u8,
    province_id: i64,
    city_id: i64,
    region_id: i64,
    address: []const u8,
    longitude: []const u8,
    latitude: []const u8,
    geohash: []const u8,
    summary: []const u8,
    sort: i64,
    is_check: i64,
    status: i64,
    shop_supplier_id: ?i64,
    is_delete: i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("store_id");
        try jws.write(self.store_id);
        try jws.objectField("store_name");
        try jws.write(self.store_name);
        try jws.objectField("logo_image_id");
        try jws.write(self.logo_image_id);
        try jws.objectField("linkman");
        try jws.write(self.linkman);
        try jws.objectField("phone");
        try jws.write(self.phone);
        try jws.objectField("shop_hours");
        try jws.write(self.shop_hours);
        try jws.objectField("province_id");
        try jws.write(self.province_id);
        try jws.objectField("city_id");
        try jws.write(self.city_id);
        try jws.objectField("region_id");
        try jws.write(self.region_id);
        try jws.objectField("address");
        try jws.write(self.address);
        try jws.objectField("longitude");
        try jws.write(self.longitude);
        try jws.objectField("latitude");
        try jws.write(self.latitude);
        try jws.objectField("geohash");
        try jws.write(self.geohash);
        try jws.objectField("summary");
        try jws.write(self.summary);
        try jws.objectField("sort");
        try jws.write(self.sort);
        try jws.objectField("is_check");
        try jws.write(self.is_check);
        try jws.objectField("status");
        try jws.write(self.status);
        try jws.objectField("shop_supplier_id");
        if (self.shop_supplier_id) |v| try jws.write(v) else try jws.write(null);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduStoreClerk = struct {
    pub const sql_table_name: []const u8 = "zmodu_store_clerk";
    clerk_id: i64,
    store_id: i64,
    user_id: i64,
    real_name: []const u8,
    mobile: []const u8,
    status: i64,
    shop_supplier_id: i64,
    is_delete: i64,
    app_id: i64,
    create_time: i64,
    update_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("clerk_id");
        try jws.write(self.clerk_id);
        try jws.objectField("store_id");
        try jws.write(self.store_id);
        try jws.objectField("user_id");
        try jws.write(self.user_id);
        try jws.objectField("real_name");
        try jws.write(self.real_name);
        try jws.objectField("mobile");
        try jws.write(self.mobile);
        try jws.objectField("status");
        try jws.write(self.status);
        try jws.objectField("shop_supplier_id");
        try jws.write(self.shop_supplier_id);
        try jws.objectField("is_delete");
        try jws.write(self.is_delete);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.objectField("update_time");
        try jws.write(self.update_time);
        try jws.endObject();
    }
};

pub const ZmoduStoreOrder = struct {
    pub const sql_table_name: []const u8 = "zmodu_store_order";
    id: i64,
    order_id: i64,
    order_type: i64,
    store_id: i64,
    clerk_id: i64,
    shop_supplier_id: i64,
    verify_num: i64,
    verify_status: i64,
    cancel_time: i64,
    app_id: i64,
    create_time: i64,

    pub fn jsonStringify(self: @This(), jws: anytype) !void {
        try jws.beginObject();
        try jws.objectField("id");
        try jws.write(self.id);
        try jws.objectField("order_id");
        try jws.write(self.order_id);
        try jws.objectField("order_type");
        try jws.write(self.order_type);
        try jws.objectField("store_id");
        try jws.write(self.store_id);
        try jws.objectField("clerk_id");
        try jws.write(self.clerk_id);
        try jws.objectField("shop_supplier_id");
        try jws.write(self.shop_supplier_id);
        try jws.objectField("verify_num");
        try jws.write(self.verify_num);
        try jws.objectField("verify_status");
        try jws.write(self.verify_status);
        try jws.objectField("cancel_time");
        try jws.write(self.cancel_time);
        try jws.objectField("app_id");
        try jws.write(self.app_id);
        try jws.objectField("create_time");
        try jws.write(self.create_time);
        try jws.endObject();
    }
};

