//! Auto-generated service for module: store
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/
//!
//! ╔═══════════════════════════════════════════════════════════╗
//! ║  AI Metadata: module=store | layer=service      ║
//! ║  role=CRUD delegation | extends=service_ext.zig           ║
//! ╚═══════════════════════════════════════════════════════════╝

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");
const persistence = @import("persistence.zig");

pub const StoreService = struct {
    persistence: *persistence.StorePersistence,
    // EventBus — uncomment to enable event-driven communication:
    // event_bus: zigmodu.TypedEventBus(StoreEvent),

    pub fn init(persistence_ptr: *persistence.StorePersistence) StoreService {
        return .{ .persistence = persistence_ptr };
    }

    // Event hooks (uncomment and define event types to enable):
    // fn afterCreate(self: *StoreService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterUpdate(self: *StoreService, entity: anytype) !void {
    //     try self.event_bus.publish(.{ .id = entity.id });
    // }
    // fn afterDelete(self: *StoreService, id: i64) !void {
    //     try self.event_bus.publish(.{ .id = id });
    // }

    pub fn listZmoduStores(self: *StoreService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduStore) {
        var repo = self.persistence.zmoduStoreRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduStore(self: *StoreService, id: i64) !?model.ZmoduStore {
        var repo = self.persistence.zmoduStoreRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduStore(self: *StoreService, entity: model.ZmoduStore) !model.ZmoduStore {
        var repo = self.persistence.zmoduStoreRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduStore(self: *StoreService, entity: model.ZmoduStore) !void {
        var repo = self.persistence.zmoduStoreRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduStore(self: *StoreService, id: i64) !void {
        var repo = self.persistence.zmoduStoreRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduStoreClerks(self: *StoreService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduStoreClerk) {
        var repo = self.persistence.zmoduStoreClerkRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduStoreClerk(self: *StoreService, id: i64) !?model.ZmoduStoreClerk {
        var repo = self.persistence.zmoduStoreClerkRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduStoreClerk(self: *StoreService, entity: model.ZmoduStoreClerk) !model.ZmoduStoreClerk {
        var repo = self.persistence.zmoduStoreClerkRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduStoreClerk(self: *StoreService, entity: model.ZmoduStoreClerk) !void {
        var repo = self.persistence.zmoduStoreClerkRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduStoreClerk(self: *StoreService, id: i64) !void {
        var repo = self.persistence.zmoduStoreClerkRepo();
        return try repo.delete(id);
    }

    pub fn listZmoduStoreOrders(self: *StoreService, page: usize, size: usize) !zigmodu.orm.PageResult(model.ZmoduStoreOrder) {
        var repo = self.persistence.zmoduStoreOrderRepo();
        return try repo.findPage(page, size);
    }

    pub fn getZmoduStoreOrder(self: *StoreService, id: i64) !?model.ZmoduStoreOrder {
        var repo = self.persistence.zmoduStoreOrderRepo();
        return try repo.findById(id);
    }

    pub fn createZmoduStoreOrder(self: *StoreService, entity: model.ZmoduStoreOrder) !model.ZmoduStoreOrder {
        var repo = self.persistence.zmoduStoreOrderRepo();
        return try repo.insert(entity);
    }

    pub fn updateZmoduStoreOrder(self: *StoreService, entity: model.ZmoduStoreOrder) !void {
        var repo = self.persistence.zmoduStoreOrderRepo();
        return try repo.update(entity);
    }

    pub fn deleteZmoduStoreOrder(self: *StoreService, id: i64) !void {
        var repo = self.persistence.zmoduStoreOrderRepo();
        return try repo.delete(id);
    }

};
