//! Auto-generated HTTP API for module: admin
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const AdminApi = struct {
    service: *service.AdminService,

    pub fn init(service_ptr: *service.AdminService) AdminApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *AdminApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_admin_users", listZmoduAdminUsers, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_admin_users/:id", getZmoduAdminUser, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_admin_users", createZmoduAdminUser, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_admin_users/:id", updateZmoduAdminUser, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_admin_users/:id", deleteZmoduAdminUser, @ptrCast(@alignCast(self)));
    }

    fn listZmoduAdminUsers(ctx: *zigmodu.http_server.Context) !void {
        const self: *AdminApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[admin] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[admin] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduAdminUsers(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduAdminUser(ctx: *zigmodu.http_server.Context) !void {
        const self: *AdminApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[admin] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[admin] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduAdminUser(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduAdminUser(ctx: *zigmodu.http_server.Context) !void {
        const self: *AdminApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduAdminUser) catch {
            std.log.warn("[admin] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduAdminUser(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduAdminUser(ctx: *zigmodu.http_server.Context) !void {
        const self: *AdminApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduAdminUser) catch {
            std.log.warn("[admin] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduAdminUser(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduAdminUser(ctx: *zigmodu.http_server.Context) !void {
        const self: *AdminApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[admin] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduAdminUser(id);
        try ctx.json(204, "");
    }

};
