//! Auto-generated ORM persistence for module: admin
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const AdminPersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) AdminPersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduAdminUserRepo(self: *AdminPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduAdminUser) {
        return .{ .orm = &self.orm };
    }

};
