//! zmsaas backend — zigmodu SaaS business example.
//! One org-scoped business module (`orders`) generated by `zmodu saas`,
//! mounted with the framework's best-practice auth stack:
//! JWT(catalog) → module gate → permission gate → data permission.
//!
//! Run:  cd examples/zmsaas/backend && zig build run
//! Login: POST /api/v1/auth/login  ->  {"token":"..."}  (tenant 1, admin)
//! API:   GET/POST /api/v1/orders (JWT, tenant-scoped), /{id} PUT/DELETE

const std = @import("std");
const zigmodu = @import("zigmodu");

const orders_mod = @import("modules/orders/root.zig");
const auth_mod = @import("auth/root.zig");
const middleware = @import("middleware/root.zig");
const schema = @import("db/schema.zig");

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;

    const sqlite_path = init.environ_map.get("ZFSAAS_SQLITE") orelse ":memory:";
    var db_client = zigmodu.data.Client.init(allocator, io, .{
        .driver = .sqlite,
        .sqlite_path = sqlite_path,
    });
    defer db_client.deinit();
    try db_client.connect();
    try schema.apply(&db_client);
    try schema.grants(&db_client);
    std.log.info("[zmsaas] sqlite ready at {s}", .{sqlite_path});

    const port: u16 = blk: {
        if (init.environ_map.get("ZFSAAS_PORT")) |p| {
            break :blk std.fmt.parseInt(u16, p, 10) catch 18080;
        }
        break :blk 18080;
    };
    var server = zigmodu.http.Server.init(io, allocator, port);
    defer server.deinit();

    // ── Auth stack (ROUTE_TABLE §7 Path A) ──────────────
    const jwt_secret = init.environ_map.get("JWT_SECRET") orelse "zmsaas-dev-secret";
    var app_sec = zigmodu.security.AppSecurity.init(allocator, io, .{ .jwt_secret = jwt_secret });
    auth_mod.g_sec = &app_sec;
    var catalog_slot: zigmodu.http.CatalogSlot = .{};
    defer catalog_slot.deinit();
    try server.addMiddleware(middleware.tenantMiddleware());
    try server.addMiddleware(middleware.jwtAuthMiddleware(&app_sec.module, &catalog_slot, &db_client));
    try server.addMiddleware(middleware.moduleGateMiddleware(&catalog_slot));
    try server.addMiddleware(middleware.permissionGateMiddleware(&catalog_slot));
    try server.addMiddleware(middleware.dataPermissionMiddleware());

    // ── Business module (generated by zmodu saas) ────────
    var backend = zigmodu.data.SqlxBackend{ .allocator = allocator, .client = &db_client };
    var persist = orders_mod.persistence.OrdersPersistence.init(&backend);
    var svc = orders_mod.service.OrdersService.init(&persist);
    var api = orders_mod.api.OrdersApi.init(&svc);
    var actions_api = orders_mod.api.OrdersActionsApi.init(&svc);
    var auth_api = auth_mod.AuthApi{};

    // CRUD 即事件源：写操作（含自定义 cancel 走的 crud.update）自动 publish，
    // 订阅方做解耦副作用（日志/通知/审计/外发）。
    var order_bus = zigmodu.TypedEventBus(zigmodu.data.CrudEvent(orders_mod.model.Orders)).init(allocator);
    defer order_bus.deinit();
    try order_bus.subscribe(orders_mod.events.onOrderEvent);
    svc.crud.setEventBus(&order_bus);

    const AppState = struct {};
    var app_state: AppState = .{};
    const OrdersApiT = @TypeOf(api);
    const OrdersActionsApiT = @TypeOf(actions_api);
    const AuthApiT = @TypeOf(auth_api);
    comptime zigmodu.http.assertNoDupes(.{ OrdersApiT, OrdersActionsApiT, AuthApiT });
    var router = zigmodu.http.Router(AppState).init(io, allocator, &server, &app_state);
    defer router.deinit();
    var api_v1 = router.scope("/api/v1");
    try api_v1.mountAll(.{
        .{ .Mod = AuthApiT, .state = &auth_api },
        .{ .Mod = OrdersApiT, .state = &api },
        .{ .Mod = OrdersActionsApiT, .state = &actions_api },
    });
    catalog_slot.set(try router.finish());
    std.log.info("[zmsaas] route catalog: {d} entries", .{catalog_slot.get().?.entries.len});

    try server.addRoute(.{
        .method = .GET,
        .path = "health/live",
        .handler = struct {
            fn handle(ctx: *zigmodu.http.Context) !void {
                try ctx.json(200, "{\"status\":\"UP\"}");
            }
        }.handle,
    });

    std.log.info("[zmsaas] http://0.0.0.0:{d}/api/v1/orders (JWT required)", .{port});
    try server.start();
}
