//! zmsaas backend — zigmodu SaaS business example.
//! One org-scoped business module (`orders`) generated by `zmodu saas`,
//! mounted with the framework's best-practice auth stack:
//! JWT(catalog) → module gate → permission gate → data permission.
//!
//! Run:  cd examples/zmsaas/backend && zig build run
//! Login: POST /api/v1/auth/login  ->  {"token":"..."}  (tenant 1, admin)
//! API:   GET/POST /api/v1/orders (JWT, tenant-scoped), /{id} PUT/DELETE

const std = @import("std");
const zigmodu = @import("zigmodu");

const orders_mod = @import("modules/orders/root.zig");
const auth_mod = @import("auth/root.zig");
const middleware = @import("middleware/root.zig");
const schema = @import("db/schema.zig");
const ops = @import("ops.zig");
const shard = @import("shard.zig");

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;

    const sqlite_path = init.environ_map.get("ZFSAAS_SQLITE") orelse ":memory:";
    // 文件 DB 用连接池（cron outbox 后台线程与请求线程共用，线程安全）；
    // :memory: 每连接独立库，保持单连接。
    const pooled = !std.mem.eql(u8, sqlite_path, ":memory:");
    var db_client = zigmodu.data.Client.init(allocator, io, .{
        .driver = .sqlite,
        .sqlite_path = sqlite_path,
        .max_open_conns = if (pooled) 4 else 1,
        .max_idle_conns = if (pooled) 2 else 1,
    });
    defer db_client.deinit();
    try db_client.connect();
    db_client.warmPool();
    try schema.apply(&db_client, allocator);
    try schema.grants(&db_client);
    std.log.info("[zmsaas] sqlite ready at {s}", .{sqlite_path});

    const port: u16 = blk: {
        if (init.environ_map.get("ZFSAAS_PORT")) |p| {
            break :blk std.fmt.parseInt(u16, p, 10) catch 18080;
        }
        break :blk 18080;
    };
    var server = zigmodu.http.Server.init(io, allocator, port);
    defer server.deinit();

    // ── Auth stack (ROUTE_TABLE §7 Path A) ──────────────
    const jwt_secret = init.environ_map.get("JWT_SECRET") orelse "zmsaas-dev-secret";
    var app_sec = zigmodu.security.AppSecurity.init(allocator, io, .{ .jwt_secret = jwt_secret });
    auth_mod.g_sec = &app_sec;
    var catalog_slot: zigmodu.http.CatalogSlot = .{};
    defer catalog_slot.deinit();
    try server.addMiddleware(middleware.tenantMiddleware());
    // 请求级可观测：注入 x-trace-id + 记录耗时（一行启用，全路由生效）。
    try server.addMiddleware(zigmodu.http.tracingMiddleware());
    // 请求计数（Prometheus 格式，GET /metrics 暴露）。
    var metrics = zigmodu.observability.PrometheusMetrics.init(allocator);
    defer metrics.deinit();
    const req_counter = try metrics.createCounter("http_requests_total", "Total HTTP requests");
    try server.addMiddleware(.{
        .func = struct {
            fn mw(ctx: *zigmodu.http.Context, next: zigmodu.http.HandlerFn, user_data: ?*anyopaque) anyerror!void {
                const c: *zigmodu.observability.PrometheusMetrics.Counter = @ptrCast(@alignCast(user_data orelse return error.NoMetrics));
                c.inc();
                try next(ctx);
            }
        }.mw,
        .user_data = @ptrCast(@constCast(req_counter)),
    });
    try metrics.registerMetricsRoute(&server);
    try server.addMiddleware(middleware.jwtAuthMiddleware(&app_sec.module, &catalog_slot, &db_client));
    try server.addMiddleware(middleware.moduleGateMiddleware(&catalog_slot));
    try server.addMiddleware(middleware.permissionGateMiddleware(&catalog_slot));
    try server.addMiddleware(middleware.dataPermissionMiddleware());

    // ── Business module (generated by zmodu saas) ────────
    var backend = zigmodu.data.SqlxBackend{ .allocator = allocator, .client = &db_client };
    var persist = orders_mod.persistence.OrdersPersistence.init(&backend);
    var svc = orders_mod.service.OrdersService.init(&persist);
    var api = orders_mod.api.OrdersApi.init(&svc);
    var actions_api = orders_mod.api.OrdersActionsApi.init(&svc);
    var ops_api = ops.OpsApi.init(&db_client);
    const shard_dir = init.environ_map.get("ZFSAAS_SHARD_DIR") orelse "/tmp";
    var shard_api = try shard.ShardApi.init(allocator, io, shard_dir);
    var auth_api = auth_mod.AuthApi{};

    // CRUD 即事件源：写操作（含自定义 cancel 走的 crud.update）自动 publish，
    // 订阅方做解耦副作用（日志/通知/审计/外发）。
    var order_bus = zigmodu.TypedEventBus(zigmodu.data.CrudEvent(orders_mod.model.Orders)).init(allocator);
    defer order_bus.deinit();
    try order_bus.subscribe(orders_mod.events.onOrderEvent);
    svc.crud.setEventBus(&order_bus);

    const AppState = struct {};
    var app_state: AppState = .{};
    const OrdersApiT = @TypeOf(api);
    const OrdersActionsApiT = @TypeOf(actions_api);
    const OpsApiT = @TypeOf(ops_api);
    const ShardApiT = @TypeOf(shard_api);
    const AuthApiT = @TypeOf(auth_api);
    comptime zigmodu.http.assertNoDupes(.{ OrdersApiT, OrdersActionsApiT, OpsApiT, ShardApiT, AuthApiT });
    var router = zigmodu.http.Router(AppState).init(io, allocator, &server, &app_state);
    defer router.deinit();
    var api_v1 = router.scope("/api/v1");
    try api_v1.mountAll(.{
        .{ .Mod = AuthApiT, .state = &auth_api },
        .{ .Mod = OrdersApiT, .state = &api },
        .{ .Mod = OrdersActionsApiT, .state = &actions_api },
        .{ .Mod = OpsApiT, .state = &ops_api },
        .{ .Mod = ShardApiT, .state = &shard_api },
    });
    catalog_slot.set(try router.finish());
    std.log.info("[zmsaas] route catalog: {d} entries", .{catalog_slot.get().?.entries.len});

    try server.addRoute(.{
        .method = .GET,
        .path = "health/live",
        .handler = struct {
            fn handle(ctx: *zigmodu.http.Context) !void {
                try ctx.json(200, "{\"status\":\"UP\"}");
            }
        }.handle,
    });

    // Readiness：/health/ready 汇总注册的健康检查（含 DB 连通性）。
    var health = zigmodu.HealthEndpoint.init(allocator);
    defer health.deinit();
    try health.registerCheckWithContext("db", "sqlite connectivity", dbCheck, &db_client);
    try server.addRoute(.{
        .method = .GET,
        .path = "health/ready",
        .handler = struct {
            fn handle(ctx: *zigmodu.http.Context) !void {
                const h: *zigmodu.HealthEndpoint = @ptrCast(@alignCast(ctx.user_data orelse return error.NoHealth));
                const body = try h.toJson(ctx.allocator);
                defer ctx.allocator.free(body);
                try ctx.setHeader("Content-Type", "application/json");
                try ctx.text(200, body);
            }
        }.handle,
        .user_data = &health,
    });

    std.log.info("[zmsaas] http://0.0.0.0:{d}/api/v1/orders (JWT required)", .{port});

    // ── Outbox cron 投递（文件 DB + 池化 client）──────────────
    var outbox_scheduler: ?zigmodu.cron.Scheduler = null;
    if (pooled) {
        var sched = zigmodu.cron.Scheduler.init(allocator, io);
        const expr = try zigmodu.cron.Expression.parse("* * * * *");
        const OutboxCtx = struct { allocator: std.mem.Allocator, client: *zigmodu.data.Client };
        const outbox_ctx = try allocator.create(OutboxCtx);
        outbox_ctx.* = .{ .allocator = allocator, .client = &db_client };
        try sched.addJob("outbox", expr, outboxCronTick, outbox_ctx);
        try sched.start();
        outbox_scheduler = sched;
        std.log.info("[zmsaas] outbox cron worker started (every minute, pooled client)", .{});
    }
    defer if (outbox_scheduler) |*s| s.stop();

    try server.start();
}

fn outboxCronTick(user_data: *anyopaque) void {
    const ctx: *struct { allocator: std.mem.Allocator, client: *zigmodu.data.Client } = @ptrCast(@alignCast(user_data));
    ops.deliverPending(ctx.allocator, ctx.client) catch |err| {
        std.log.err("[outbox] cron delivery failed: {s}", .{@errorName(err)});
    };
}

fn dbCheck(user_data: ?*anyopaque) zigmodu.HealthEndpoint.HealthStatus {
    const client: *zigmodu.data.Client = @ptrCast(@alignCast(user_data orelse return .DOWN));
    _ = client.queryRow(struct { one: i64 }, "SELECT 1 AS one", &.{}) catch return .DOWN;
    return .UP;
}
