#!/usr/bin/env bash
# gen-certs.sh — mint the demo PKI for the cluster-sidecar example.
#
#   ./gen-certs.sh            # generate into ./certs (skip if already present)
#   ./gen-certs.sh --force    # regenerate everything
#
# Produces (all under certs/, mode 600 for keys/env):
#   ca.key / ca.crt           demo CA (never leaves this directory)
#   node{1,2,3}.key/.crt      per-node cert, CN=nodeN, SAN=IP:172.28.0.1N
#   cluster.env               HMAC key material sourced by docker-compose:
#                             CLUSTER_SECRET / BUS_KEY / KEY_N1..3 (frame auth)
#
# The certs give the *transport* (mTLS between sidecars); the hex keys give
# *frame* authentication (A-1/A-3, HMAC-SHA256 per frame). They answer
# different questions and both are required — see README.md.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/certs"

if [ "${1:-}" = "--force" ]; then
  rm -rf "$OUT"
fi
if [ -f "$OUT/ca.crt" ] && [ -f "$OUT/cluster.env" ]; then
  echo "gen-certs: $OUT already populated (use --force to regenerate)"
  exit 0
fi
mkdir -p "$OUT"
chmod 700 "$OUT"

# ── CA ──────────────────────────────────────────────────────────────────────
openssl genrsa -out "$OUT/ca.key" 4096 2>/dev/null
openssl req -x509 -new -nodes -key "$OUT/ca.key" -sha256 -days 3650 \
  -subj "/CN=zigmodu-cluster-sidecar-demo-ca" -out "$OUT/ca.crt"

# ── per-node certs (SAN carries the static compose IP; nginx verifies the
#    peer name against it — the IP *is* the identity at this layer) ──────────
for i in 1 2 3; do
  ip="172.28.0.1$i"
  openssl genrsa -out "$OUT/node$i.key" 2048 2>/dev/null
  openssl req -new -key "$OUT/node$i.key" -subj "/CN=node$i" -out "$OUT/node$i.csr"
  ext="$(mktemp)"
  # Both SAN forms, deliberately: nginx's upstream verification (proxy_ssl_verify)
  # goes through X509_check_host, which does NOT consult iPAddress SANs — a cert
  # carrying only `IP:…` is rejected ("upstream SSL certificate does not match"),
  # measured with nginx 1.27.5. The DNS-form entry is matched as a plain string.
  printf 'subjectAltName=IP:%s,DNS:%s\n' "$ip" "$ip" >"$ext"
  openssl x509 -req -in "$OUT/node$i.csr" -CA "$OUT/ca.crt" -CAkey "$OUT/ca.key" \
    -CAcreateserial -days 825 -sha256 -extfile "$ext" -out "$OUT/node$i.crt"
  rm -f "$ext" "$OUT/node$i.csr"
done
rm -f "$OUT/ca.srl"

# ── frame-auth key material (NOT tls — these are the HMAC keys the framework
#    itself uses; gen them here so compose has one env file to source) ───────
{
  echo "# generated by gen-certs.sh — demo key material, do not commit"
  echo "CLUSTER_SECRET=$(openssl rand -hex 32)"
  echo "BUS_KEY=$(openssl rand -hex 32)"
  for i in 1 2 3; do
    echo "KEY_N$i=$(openssl rand -hex 32)"
  done
} >"$OUT/cluster.env"

chmod 600 "$OUT"/*.key "$OUT/cluster.env"
chmod 644 "$OUT"/*.crt
echo "gen-certs: wrote CA + node{1,2,3} certs + cluster.env into certs/"
