//! Auto-generated HTTP API for module: setting
//! Generated by zmodu orm — uses `zigmodu.http_server` + `ctx.bindJson` / `ctx.jsonStruct`.

const std = @import("std");
const zigmodu = @import("zigmodu");
const service = @import("service.zig");
const model = @import("model.zig");

pub const SettingApi = struct {
    service: *service.SettingService,

    pub fn init(service_ptr: *service.SettingService) SettingApi {
        return .{ .service = service_ptr };
    }

    pub fn registerRoutes(self: *SettingApi, group: *zigmodu.http_server.RouteGroup) !void {
        try group.get("/zmodu_settings", listZmoduSettings, @ptrCast(@alignCast(self)));
        try group.get("/zmodu_settings/:id", getZmoduSetting, @ptrCast(@alignCast(self)));
        try group.post("/zmodu_settings", createZmoduSetting, @ptrCast(@alignCast(self)));
        try group.put("/zmodu_settings/:id", updateZmoduSetting, @ptrCast(@alignCast(self)));
        try group.delete("/zmodu_settings/:id", deleteZmoduSetting, @ptrCast(@alignCast(self)));
    }

    fn listZmoduSettings(ctx: *zigmodu.http_server.Context) !void {
        const self: *SettingApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const page_str = ctx.query.get("page") orelse "0";
        const size_str = ctx.query.get("size") orelse "10";
        const page = std.fmt.parseInt(usize, page_str, 10) catch {
            std.log.warn("[setting] list: invalid page", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid page");
            return;
        };
        const size = std.fmt.parseInt(usize, size_str, 10) catch {
            std.log.warn("[setting] list: invalid size", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid size");
            return;
        };
        const result = try self.service.listZmoduSettings(page, size);
        try ctx.jsonStruct(200, result);
    }

    fn getZmoduSetting(ctx: *zigmodu.http_server.Context) !void {
        const self: *SettingApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[setting] get: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "missing id");
            return;
        };
        const id = std.fmt.parseInt(i64, id_str, 10) catch {
            std.log.warn("[setting] get: invalid id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        const entity = try self.service.getZmoduSetting(id);
        try ctx.jsonStruct(200, entity);
    }

    fn createZmoduSetting(ctx: *zigmodu.http_server.Context) !void {
        const self: *SettingApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduSetting) catch {
            std.log.warn("[setting] create: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        const created = try self.service.createZmoduSetting(entity);
        try ctx.jsonStruct(201, created);
    }

    fn updateZmoduSetting(ctx: *zigmodu.http_server.Context) !void {
        const self: *SettingApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const entity = ctx.bindJson(model.ZmoduSetting) catch {
            std.log.warn("[setting] update: invalid body", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid body");
            return;
        };
        try self.service.updateZmoduSetting(entity);
        try ctx.jsonStruct(200, entity);
    }

    fn deleteZmoduSetting(ctx: *zigmodu.http_server.Context) !void {
        const self: *SettingApi = @ptrCast(@alignCast(ctx.user_data orelse return error.InternalError));
        const id_str = ctx.params.get("id") orelse {
            std.log.warn("[setting] delete: missing id", .{});
            try ctx.sendErrorResponse(400, @intFromEnum(zigmodu.HttpCode.BadRequest), "invalid id");
            return;
        };
        try self.service.deleteZmoduSetting(id);
        try ctx.json(204, "");
    }

};
