//! Auto-generated ORM persistence for module: setting
//! Generated by zmodu orm — templates: tools/zmodu/src/templates/orm/sqlx/

const std = @import("std");
const zigmodu = @import("zigmodu");
const model = @import("model.zig");

pub const SettingPersistence = struct {
    backend: zigmodu.SqlxBackend,
    orm: zigmodu.orm.Orm(zigmodu.SqlxBackend),

    pub fn init(backend: zigmodu.SqlxBackend) SettingPersistence {
        return .{ .backend = backend, .orm = .{ .backend = backend } };
    }

    pub fn zmoduSettingRepo(self: *SettingPersistence) zigmodu.orm.Orm(zigmodu.SqlxBackend).Repository(model.ZmoduSetting) {
        return .{ .orm = &self.orm };
    }

};
