// Generated by zsaas gen-business — orders entity + UI field schema.
// Shared by DataTable / EntityForm so the CRUD screen is data-driven.

export type Orders = {
  id: number;
  customer: string;
  amount?: number;
  status?: string;
  notes?: string;
};

export type OrdersField = {
  name: string;
  label: string;
  type: 'text' | 'number' | 'textarea' | 'select';
  required?: boolean;
  options?: { value: string; label: string }[];
  placeholder?: string;
};

export const OrdersFields: OrdersField[] = [
  { name: 'customer', label: 'Customer', type: 'text', required: true},
  { name: 'amount', label: 'Amount (分)', type: 'number'},
  { name: 'status', label: 'Status', type: 'select', options: [{"value":"pending","label":"Pending"},{"value":"paid","label":"Paid"},{"value":"cancelled","label":"Cancelled"}]},
  { name: 'notes', label: 'Notes', type: 'textarea'},
];
